### ISSUE TITLE
ingest and display failed transactions

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#100]
Transactions that fail during consensus should be ingested, query-able and be counted in statistics aggregation. This will help in providing a better audit trail and insights into actual network capacity. 

There's a similar issue on horizon: https://github.com/stellar/go/issues/711

**Comment by orbitlens** [comment]
Currently the ingestion engine processes failed transactions to extract paid fees information. With current data structure failed transactions can be easily calculated, but that's all the information that can retrieved. Using failed transactions in stat counters leads to effectively doubled storage size for statistics because for each asset|account data entry I need to save not only the "successful" stats, but also the number of failed payments, trades, trustlines, trading volumes etc.

It's possible, but I can't guarantee that failed tx stats will be implemented earlier than Q2 2019. For now, I can generate a chart with overall failed transaction counter, like [here](https://twitter.com/orbitlens/status/1038810997853769728).

**Comment by tomerweller** [comment]
I don't see a need to actually "ingest" failed operations or anything that relates to the account page. 
I think that the resources that are currently misleading are the ledger resource page and the Ledger Activity graph. Some possible low hanging fruit: 

Ledger page
- Add another field to the header "failed transactions" which counts how many failed transactions were in this ledger.
- Maybe even list them, but without actually unpacking the operations. 

Ledger Activity Graph
- Instead of just having `Transactions` have Total Transaction (including failed) and Successful Transactions. this sho

**Comment by tomerweller** [comment]
> I understand that it will significantly increase the result JSON size, so maybe you could introduce some additional query flag for that purpose

The main problem is that this information is not currently digested by horizon. 

The only quick workaround I can think of is having a stellar-core with `CATCHUP_COMPLETE=true` (and no pruning) and query it's `txhistory` table directly, which includes failed transactions.

**Comment by orbitlens** [comment]
Yeah, I know that Horizon DB does not contain mentioned XDRs.

> The only quick workaround I can think of is having a stellar-core with CATCHUP_COMPLETE=true (and no pruning) and query it's txhistory table directly, which includes failed transactions.

That would be awesome. As far as I understand, SDF-maintained nodes retain the whole history in the DB, are they? 

I would love to contribute and implement this feature by myself, but I'm not any good with Go (

Do you mind if I push this feature request in the go monorepo issue tracker to at least start the discussion about it?

**Comment by tomerweller** [comment]
> Do you mind if I push this feature request to the go monorepo issue tracker, so at least we could start the discussion about it?

I don't mind at all. Though this will take some time. 

TBH, I was wondering/suggesting if you have such a stellar-core node or willing to run one so that you can query the db directly for this kind of information.

**Comment by orbitlens** [comment]
Well, querying the Core DB was my first thought, but that will defeat the whole idea. StellarExpert old architecture has been built on top of Core and Horizon DB. The node required regular maintenance, aggregation queries became too slow over time, materialized views grew to giant size. The whole point of the general refactor was to get rid of the Stellar node dependencies and implement direct archive files ingestion. Currently, StellarExpert relies on SDF-maintained Horizon only to stream the latest ledgers updates and display basic ledger/tx/account information in the UI. I intentionally turned off my pubnet and testnet nodes to fight the desire to query something directly from Core DB. 

If only I could retrieve the tx set and ledger results XDR information from Horizon, I could rewrite my ingestion engine to simplify the overall synchronization process, making it more reliable, and parse ledgers information directly in the browser, avoiding jumping through the hoops.

I understand that you guys are busy building more important stuff. I'll try to find someone with the required skillset from the community to implement this feature.

**Comment by tomerweller** [comment]
After thinking about this some more it seems that while https://github.com/stellar/go/issues/309 is not fixed, just adding a failed tx count to the ledger resource is a low hanging fruit that can help. added https://github.com/stellar/go/issues/754

**Comment by tomerweller** [comment]
horizon [0.16.0](https://github.com/stellar/go/commit/cffdea30514f951136e7dbd947dbc6c013c50868) is out and deployed on the public horizon instance. Ledger resources now contain `failed_transaction_count`

**Comment by orbitlens** [comment]
Implemented in `v0.8.41`
