### ISSUE TITLE
Deauthorized instead of authorized

### ISSUE THREAD

**Issue by jeffditullio** [orbitlens/stellar-expert-explorer#101]
https://stellar.expert/explorer/public/account/GBSTRUSD7IRX73RQZBL3RQUH6KS3O4NYFY3QCALDLZD77XMZOPWAVTUK?filter=settings
The title of each transaction incorrectly says deauthorized. When expanding and looking at raw data it correctly says authorized.

**Comment by orbitlens** [comment]
Fixed in `v0.8.27`
Thanks!
