### ISSUE TITLE
Remove StellarTerm sorry on the directory page

### ISSUE THREAD

**Issue by theaeolianmachine** [orbitlens/stellar-expert-explorer#112]
Hey Orbit,

It says "Special thanks to @IrisLi who maintained the original Stellar directory, sorry to see that StellarTerm is shutting down."

Probably worth still thanking Iris but removing the latter, since StellarTerm is under the Lobstr team now?

**Comment by theaeolianmachine** [comment]
Present on this page: https://stellar.expert/explorer/public/directory

**Comment by orbitlens** [comment]
Fixed in `v0.8.40`
