### ISSUE TITLE
Access asset statistics by URL

### ISSUE THREAD

**Issue by rarach** [orbitlens/stellar-expert-explorer#118]
I visit the asset statistics at https://stellar.expert/explorer/public/asset often but it's a bit annoying that I have to setup the "Sort By" filter and pagination ("Load More") all over again. Especially when I open an asset from there and then go back in browser.
I'd welcome something like https://stellar.expert/explorer/public/asset?sortBy=totalPayments&pageSize=100

**Comment by orbitlens** [comment]
Implemented in v0.9.25
