### ISSUE TITLE
NaoBTC deposit !

### ISSUE THREAD

**Issue by HB1github** [orbitlens/stellar-expert-explorer#120]
Hello,
this is not acceptable, StellarX provides NaoBTC to deposit BTC. I am waiting for my BTC credited since days!

**Comment by orbitlens** [comment]
You should contact NaoBTC support. StellarExpert is a ledger explorer and isn't affiliated with NaoBTC.

**Comment by kino6912** [comment]
Any luck with this NaoBTC just dabbed my XLM/BTC this is the address it was sent to GBTCBCWLE6YVTR5Y5RRZC36Z37OH22G773HECWEIZTZJSN4WTG3CSOES
