### ISSUE TITLE
priceChangePercent": "xx" in Open API

### ISSUE THREAD

**Issue by slideloft** [orbitlens/stellar-expert-explorer#124]
Hi.
I cant seem to find priceChangePercent in the open API for an asset, can you point it out for me if it is in the API , or make it feature request.

**Comment by orbitlens** [comment]
Currently, the asset API endpoint, as well as most other APIs, is proprietary and not intended for public use. The format, URLs, encoding may (and will) be changed without prior notice.

The list of all Open API endpoints can be found [here](https://github.com/orbitlens/stellar-expert-explorer/blob/master/docs/api/index.md).
