### ISSUE TITLE
request to update information for MIX token

### ISSUE THREAD

**Issue by xirkle** [orbitlens/stellar-expert-explorer#127]
Hi,

We updated our stellar.toml for MIX. Could you refresh your data for our MIX asset please?
https://stellar.expert/explorer/public/asset/MIX-GCBVWPMIJVXYJOMKLVPPOWI457IZK4XVWTKNQNKAUENFG2QU2VDNOPSN

Thank you.

**Comment by orbitlens** [comment]
Hey,

The *home_domain* field for the issuing account should be a domain name
(i.e. *streamix.io <http://streamix.io>*), not an url (*https://streamix.io
<https://streamix.io>*).
Stellar-enabled applications and services won't be able to fetch
stellar.toml from this URL. More info here:
https://www.stellar.org/developers/guides/issuing-assets.html#discoverablity-and-meta-information

Best,
OL

**Comment by orbitlens** [comment]
Hey,

The `home_domain` field for the issuing account should be a domain name (i.e. `streamix.io`), not an url (`https://streamix.io`).  
Stellar-enabled applications and services won't be able to fetch `stellar.toml` for your account. More info here: https://www.stellar.org/developers/guides/issuing-assets.html#discoverablity-and-meta-information
