### ISSUE TITLE
display transaction signers

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#132]
The transaction view currently displays signatures but not signers. This makes it difficult to understand which signers actually signed the transaction.

A low hanging fruit is to render the hint present in `DecoratedSignature` similarly to how it's done in [Stellar laboratory](https://github.com/stellar/laboratory/blob/076f1f83c2f771aa7c8f9dd7d4e5f8c57b52180f/src/utilities/extrapolateFromXdr.js#L101). 

A step beyond that would be to actually match a signer to the hint. This is fairly simple but requires collecting all the signers of the source accounts (of both transaction and operation, if present) and finding a match to the hint.

**Comment by orbitlens** [comment]
Implemented in v0.9.27
