### ISSUE TITLE
Show memo_type=return in a user-friendly way

### ISSUE THREAD

**Issue by s-a-y** [orbitlens/stellar-expert-explorer#134]
Feature request.

Example transaction:
https://stellar.expert/explorer/public/tx/106763231892148224#106763231892148225

Instead of showing raw base64-encoded memo you could make base64->hex conversion and show hash of the transaction, that is being refunded
or go 1 step further and link to the actual transaction

**Comment by orbitlens** [comment]
Implemented in v0.9.31
