### ISSUE TITLE
Unable to switch tax year on tax export page: Tested on FF Nightly and Canary

### ISSUE THREAD

**Issue by evan-brass** [orbitlens/stellar-expert-explorer#145]
I went to this address: https://stellar.expert/tax-export/public/ and tried to select a different tax year but it didn't change.  Tried 2019, 2017, etc but it stays at 2018

Tried from Firefox Nightly and Chrome Canary

**Comment by orbitlens** [comment]
Fixed in v0.10.6
Apologies for the long response, we've been working on extremely urgent features.

**Comment by evan-brass** [comment]
No, problem.  I was just exploring with what Stellar Expert could do.  Thanks for building it!
