### ISSUE TITLE
Asset address page displaying a blank.

### ISSUE THREAD

**Issue by ferdreyfus** [orbitlens/stellar-expert-explorer#150]
When accessing the link below, no report is displayed.

https://stellar.expert/explorer/public/asset/PORTE-GB45UYSNUCIWDZQ6FKN5CLJSAQXHNREGLZQOHJI5VXPYC5O6ZGAS4FEW.

Cheers.

**Comment by orbitlens** [comment]
Fixed in v0.10.2
Thanks for the heads up!
