### ISSUE TITLE
Wrong operation source amount in account page for path payment

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#151]
In this account page: https://stellar.expert/explorer/public/account/GD646NWXHXIAVE4DMDDGUH63MVGZ7ZJVASFZOR6FOQ3YS2SHSJEQOCBN
Operation `112024588304547841` is shown to have source amount of `420`.

However, `source_amount` is actually 400. The number shown is `source_max` (see on [horizon](https://github.com/orbitlens/stellar-expert-explorer/issues/new))

**Comment by orbitlens** [comment]
Fixed in v0.10.4
