### ISSUE TITLE
HOW CAN I REVERSE A TRANSACTION?

### ISSUE THREAD

**Issue by nleann31** [orbitlens/stellar-expert-explorer#160]
CAN I GET A REVERSAL ON A TRANSACTION I MADE FROM MY KEYBASE WALLET TO MY COINBASE WALLET???

**Comment by orbitlens** [comment]
It's impossible to reverse the transaction once it is submitted.  
You need to contact Coinbase support. They can process your deposit manually, just provide the transaction id.
