### ISSUE TITLE
LAS MONEDAS FUERON ENVIADAS Y NUNCA LLEGARON A SU DESTINATARIO

### ISSUE THREAD

**Issue by eddy9735** [orbitlens/stellar-expert-explorer#161]
Send a quantity of coins to another keybase user, and after 5 days have passed they have not arrived. What can I do or how can I solve it?
my ID is this GB7ZAFHPGMXWBPLBPEIYMZUOE76HWOUTUF2GYYAK4ZA57WBHFEQXDNCO

**Comment by orbitlens** [comment]
Looks like you transferred your funds to Coinbase: https://stellar.expert/explorer/public/account/GB7ZAFHPGMXWBPLBPEIYMZUOE76HWOUTUF2GYYAK4ZA57WBHFEQXDNCO

Every transaction to the custodial exchange requires a valid memo to be deposited on your account. It's impossible to change the memo once the transaction is submitted.  
You need to contact Coinbase support. They can process your deposit manually, just provide the transaction id.
