### ISSUE TITLE
Percent fee unit is incorrect

### ISSUE THREAD

**Issue by s-a-y** [orbitlens/stellar-expert-explorer#162]
https://stellar.expert/explorer/public/asset/BTC-GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF?filter=asset-holders&order=desc

<img width="339" alt="Screen Shot 2019-11-26 at 10 44 01 AM" src="https://user-images.githubusercontent.com/1667781/69587499-d9b63a00-1039-11ea-87e5-90b9db696a00.png">

Percent fee unit should be %

**Comment by orbitlens** [comment]
Fixed in v0.11.17
