### ISSUE TITLE
Home domain URL link doesn't contain colon in "https://"

### ISSUE THREAD

**Issue by vitchor** [orbitlens/stellar-expert-explorer#170]
When opening the Home domain link, the URL doesn't include colon in the "https://" prefix.

<img width="396" alt="Screen Shot 2019-12-17 at 11 47 26 AM" src="https://user-images.githubusercontent.com/630755/71096124-8e9ccc00-218c-11ea-81a6-c9fe0b7097d3.png">

Here's the link to reproduce it:
https://stellar.expert/explorer/public/account/GCSAZVWXZKWS4XS223M5F54H2B6XPIIXZZGP7KEAIU6YSL5HDRGCI3DG

**Comment by orbitlens** [comment]
It's because the `home_domain` account property is specified incorrectly. 

According to the [official docs](https://www.stellar.org/developers/guides/concepts/accounts.html#home-domain), it should be in FQDN format – `arst.settle.network` instead of `https://arst.settle.network`.
