### ISSUE TITLE
My Withdraw is Not Received

### ISSUE THREAD

**Issue by rizwanmahi** [orbitlens/stellar-expert-explorer#171]
Hello dear,I send my xlm to an exchange,and I forgot to give memo .so please look at that and send me xlm.
Transaction:
36b1c96bc758db55f7dae5ec1676e111e458ca649972c5f57c5e1edb53dabcc3

**Comment by Yhines10** [comment]
I did the same thing. Did you get help yet

**Comment by rajanintheus** [comment]
Same mistake I also did.

**Comment by fishcharlie** [comment]
This is not the place to raise these issues. Please contact the exchange in which you sent it to, as they are the only ones who can help.

**Comment by orbitlens** [comment]
We can't help you. You need to contact the destination exchange support team and provide details required to process your deposit manually. It's impossible to change/reverse/cancel your transaction.
