### ISSUE TITLE
Never received withdraw

### ISSUE THREAD

**Issue by rbacquie** [orbitlens/stellar-expert-explorer#172]
I didn't add the memo only send to address and never received XLM coins please help transaction ID: ea69dac191a8755fb3c436cbe62bc64a56af392d9fbcfde24dced30c0c7b5ba5

**Comment by fishcharlie** [comment]
This is not the place to raise these issues. Please contact the exchange in which you sent it to, as they are the only ones who can help.

**Comment by rbacquie** [comment]
Ok thank will contact asap

**Comment by orbitlens** [comment]
We can't help you. You need to contact the destination exchange support team and provide details required to process your deposit manually. It's impossible to change/reverse/cancel your transaction.
