### ISSUE TITLE
I sent my xlm without the memo. How do i get my xlm back to resend?

### ISSUE THREAD

**Issue by Yhines10** [orbitlens/stellar-expert-explorer#175]
Please help me I've been trying all morning to see how to resend my xlm from keybase. Because i never recieved my xlm i sent to my coinbase account because i forget to put the memo

**Comment by rajanintheus** [comment]
I also have the same issue.

**Comment by Yhines10** [comment]
Im trying to figure it out but the site haven't got back with me.

**Comment by fishcharlie** [comment]
This is not the place to raise these issues. Please contact the exchange in which you sent it to, as they are the only ones who can help.

**Comment by orbitlens** [comment]
We can't help you. You need to contact the destination exchange support team and provide details required to process your deposit manually. It's impossible to change/reverse/cancel your transaction.
