### ISSUE TITLE
withdraw without memo, please, what can i do?

### ISSUE THREAD

**Issue by yoem77** [orbitlens/stellar-expert-explorer#176]
I do a withdraw without memo, what can i do for repair the withdraw? Please

**Comment by fishcharlie** [comment]
This is not the place to raise these issues. Please contact the exchange in which you sent it to, as they are the only ones who can help.

**Comment by orbitlens** [comment]
We can't help you. You need to contact the destination exchange support team and provide details required to process your deposit manually. It's impossible to change/reverse/cancel your transaction.
