### ISSUE TITLE
Asset Not Appearing As Registered

### ISSUE THREAD

**Issue by joshuathemessenger** [orbitlens/stellar-expert-explorer#177]
Hi Orbit_Lens.

I have made several assets as of this post, within the last several hours. They all appear in the wallets, as though all is well. But, when the Tx hash, or asset is searched, it ends with an error that the asset is not listed. Please assist, thank you.

ex Tx-
https://stellar.expert/explorer/public/search?term=storage  <-- yields no results

Tx hash 8e2bccbb83943679e780905ed2abfeb3e1b57758e8b5a37207716160f6ba6b08

**Comment by orbitlens** [comment]
Hey Yeshua,
Indeed, our ingestion service stuck. I restarted it and now everything is back to normal.
We'll investigate the problem to prevent such problems in the future.
Sorry for the inconveniences.

**Comment by joshuathemessenger** [comment]
Thank you very much!
