### ISSUE TITLE
wrong representation for the asset TOTAL SUPPLY

### ISSUE THREAD

**Issue by wkta** [orbitlens/stellar-expert-explorer#18]
If you look up the custom asset I created:
[click here](https://stellar.expert/explorer/asset/GTTpresale1-GBSO63GMXZKXGY3XL3SMQIQJ2JHK4USIABOOXWXZD7P3FCLHNY7Q64XS)

the stellar.expert web app displays :
   236,000,000,000 for **Total supply** which is wrong.

The total supply of my custom asset is in fact 23,600 units.
Those tokens represent real euros that I will pay back after jan 1st 2019 to early investors that invested in my project… I obviously won't be able to pay hundreds of billions!

You can also check the HUG asset created by Jed, it should have a total supply of 5,000 HUG as stated by Jed himself.

References :
[https://www.stellar.org/blog/tokens-on-stellar/](https://www.stellar.org/blog/tokens-on-stellar/ )
  ,  STEP 6

and also :
[https://www.stellar.org/developers/guides/concepts/assets.html](https://www.stellar.org/developers/guides/concepts/assets.html)
see the  "Amount precision and representation" part

could you follow those guidelines set by Stellar creators for the community? Thank you

**Comment by orbitlens** [comment]
Yes, that was a representation bug. 
Fixed.
