### ISSUE TITLE
Buy Offer Rate not display correct.

### ISSUE THREAD

**Issue by vanphandinh** [orbitlens/stellar-expert-explorer#181]
I've created my own token: https://stellar.expert/explorer/testnet/asset/VAN-GBTLOUREIP3TEEE3OPLXUHKLQMEMFY5L343YGJQ2QVIZDLPFQY42GV7U

From Distribution Account: GANLADXO3MAYRLDQTFMS2GAKXGCSTV4EMNGDYZJT4DLN6GNG5DSNUELU
I've created a sell offer to sell 1M VAN token with price 0.2 XLM/VAN (correct):
https://stellar.expert/explorer/testnet/tx/1568354552778752#1568354552778753

From Buyer: GDYFBQECSCCT7BXF5L4D6I7KL743NJI7CV6EPI6OCPHTW2B4QWATZTLL
I've created some buy offers to buy VAN token: 
https://stellar.expert/explorer/testnet/account/GDYFBQECSCCT7BXF5L4D6I7KL743NJI7CV6EPI6OCPHTW2B4QWATZTLL?filter=offers
The last 3 offers are executed by rate 0.2, 5 and 10
The latest offer is on active by rate of 0.1

I think the rate should be XLM/VAN or you should take the inverse of the rate to correct the rate.
<img width="1192" alt="Screen Shot 2020-02-21 at 5 59 58 PM" src="https://user-images.githubusercontent.com/13887599/75029109-0ad8c600-54d4-11ea-9293-a22a8229942e.png">
<img width="1178" alt="Screen Shot 2020-02-21 at 6 00 07 PM" src="https://user-images.githubusercontent.com/13887599/75029114-0c09f300-54d4-11ea-9402-302c236ee551.png">

You can see, the rate of the latest offer in the Offers tab and the Active Offers tab are different

**Comment by orbitlens** [comment]
Confirmed. We are working on a fix for this.
Thanks for the bug report.

**Comment by orbitlens** [comment]
Fxied
