### ISSUE TITLE
navigate by op_id leads to the wrong transaction

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#183]
steps to recreate: 
- search for the term: `121717109720895489`
- click on the first search result
- you're in the wrong transaction page. you should be [here](https://stellar.expert/explorer/public/tx/c958fb435e574df64f738085615c1f47d7145e5328eba80bee06b762337d3cab) but you're [here](https://stellar.expert/explorer/public/tx/121717109720895488#121717109720895489).

note: clicking the `Transaction` link on the search result puts you in the right page.

**Comment by orbitlens** [comment]
Operation `121717109720895489` belongs to the failed transaction. The generic id of the transaction points to another tx (the closest successful tx). 

It's a bug on our side. The fix will be ready by tomorrow.

**Comment by orbitlens** [comment]
Fixed
