### ISSUE TITLE
I didn’t include memo sending lumens and now coins are not showing up 

### ISSUE THREAD

**Issue by sanchosway** [orbitlens/stellar-expert-explorer#184]
I didn’t include memo sending lumens and now coins are not showing up

**Comment by topikmaulana** [comment]
Ka kalo saya salah kirain di suruh bikin kode memo biat cari atau ngingetnya gampang eh gak tau udh ada .. Gimana ini ya saldo saya berhasil tpi gak bakal masuk ke siapa siapa . tapi saya sudah laporan ko ke pusat coinbose nya gimana ini ya ka

**Comment by orbitlens** [comment]
We can't help you. You need to contact the destination exchange support team and provide details required to process your deposit manually. It's impossible to change/reverse/cancel your transaction.
