### ISSUE TITLE
"Markets" link in search results point to asset holders

### ISSUE THREAD

**Issue by chriserice** [orbitlens/stellar-expert-explorer#191]
When searching for an asset, the "Markets" and "Top holders" are pointing to the same location. For example, if I click on apay.io's BTC markets link via [search](https://stellar.expert/explorer/public/search?term=apay.io), I'm expecting a link to its respective [markets page](https://stellar.expert/explorer/public/market/XLM/BTC-GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF) or perhaps a list of the asset's pair(s) within the markets feature.

**Comment by orbitlens** [comment]
Implemented in v15
