### ISSUE TITLE
Stellar account issue

### ISSUE THREAD

**Issue by iamchops666** [orbitlens/stellar-expert-explorer#193]
When clicking on view stellar account on nodle I am sent to a page that states my account doesn't exist on stellar ledger. Wondering if this is the reason behind not receiving the nodle rewards. I'm new to this so really any information helps. Nodle is linked to my zion wallet on HTC exodus 1. Do I create an account? How does one initiate that?

**Comment by orbitlens** [comment]
Please provide a link on StellarExpert to the account page you mentioned, I'll check if your account really exists on the ledger.

As for Nodle rewards, I have no idea how Nodle works. So if you have questions regarding accounts and Nodle tokens, you need to contact their support.

**Comment by iamchops666** [comment]
https://stellar.expert/explorer/public/account/GBBCB44GXLSU6FHX2MD4LIBV35ZOAUE2EB72PUGDK2KLDKXYZUOYA4CDOn May 10, 2020 10:28 PM, orbitlens <notifications@github.com> wrote:
Please provide a link on StellarExpert to the account page you mentioned, I'll check if your account really exists on the ledger.
As for Nodle rewards, I have no idea how Nodle works. So if you have questions regarding accounts and Nodle tokens, you need to contact their support.

**Comment by iamchops666** [comment]
Does a wallet address work too?On May 15, 2020 7:10 PM, noelchops@outlook.com wrote:https://stellar.expert/explorer/public/account/GBBCB44GXLSU6FHX2MD4LIBV35ZOAUE2EB72PUGDK2KLDKXYZUOYA4CDOn May 10, 2020 10:28 PM, orbitlens <notifications@github.com> wrote:
Please provide a link on StellarExpert to the account page you mentioned, I'll check if your account really exists on the ledger.
As for Nodle rewards, I have no idea how Nodle works. So if you have questions regarding accounts and Nodle tokens, you need to contact their support.

**Comment by orbitlens** [comment]
Account `GBBCB44GXLSU6FHX2MD4LIBV35ZOAUE2EB72PUGDK2KLDKXYZUOYA4CD` does not exists on the network. It has zero balance and no transactions history.

You need to contact Nodle support team and ask them about your account.
