### ISSUE TITLE
Transaction sequence numbers not displaying correctly

### ISSUE THREAD

**Issue by JChlipala** [orbitlens/stellar-expert-explorer#194]
Transaction sequence numbers are not being displayed correctly. It appears that instead of showing the sequence number, it is showing the first operation number minus one. For example, here is a transaction on Stellar Expert:
https://stellar.expert/explorer/public/tx/123426326316433408#123426326316433409

And here is the same transaction viewed using Stellar Laboratory:
https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6ImRlYmM4ZDVmZDEwZDM5NDc4ZGZlZjJhYmUzOGIzOGUxYmMzZTExMDU4ZTA3NzE5OWFhODM1M2IyMTJkNmI5M2EifQ%3D%3D&network=public

The sequence numbers do not match.

**Comment by bartekn** [comment]
Looks like `paging_token` is used instead of `source_account_sequence`.

**Comment by orbitlens** [comment]
Fixed in v0.13.5
