### ISSUE TITLE
Transfer from one exchange is not showing up on destiny exchange

### ISSUE THREAD

**Issue by kdalcico** [orbitlens/stellar-expert-explorer#198]
Hi,
I made a transfer from an exchange, but I don't know if the transaction has completed or not. In the source exchange is showing a message that tokens were transfered, they are not in P2PB2B wallet, could you check where it is?
![wallet and memo](https://user-images.githubusercontent.com/66035550/83065630-2d7dfc00-a03a-11ea-8f92-9d81b6770449.png)

**Comment by orbitlens** [comment]
I can see the only transaction with such memo: https://stellar.expert/explorer/public/tx/128530375256698880#128530375256698881
Hope this helps.
