### ISSUE TITLE
on the all assets page, if you load more and then sort it is weird

### ISSUE THREAD

**Issue by jedmccaleb** [orbitlens/stellar-expert-explorer#20]
https://stellar.expert/explorer/asset  
to repro click "load more" at the bottom and then sort by "trustlines" 

Also the sort by title should correspond to the column header. So sort by "holders" would be better

**Comment by alamsyah88** [comment]
@jedmccaleb hello sir , can you help me ? I have problem about my old wallet of stellar, , i cant upgrade because i forgot that email registered 😢😢 ..

**Comment by orbitlens** [comment]
- [x] Reset paging to 0 on filter change.
- [x] Rename order by "trustlines" to "asset holders"

**Comment by alamsyah88** [comment]
@jedmccaleb hello sir , can you help me ? I have problem about my old wallet of stellar, , i cant upgrade because i forgot that email registered 😢😢 ..
