### ISSUE TITLE
lost 

### ISSUE THREAD

**Issue by dpsdom** [orbitlens/stellar-expert-explorer#201]
hello , 
some months ago I sent  some coins to my wallet 
GCPVD53G4KMVXSADSANSAW4NEXHN55SYQ5YP7HKKZDP3D43IDHZFLTA7  but it never arrived as I think I did not add a comment

is there any way of trying to get these back 

regards Dominic

**Comment by orbitlens** [comment]
[Here](https://stellar.expert/explorer/public/account/GCPVD53G4KMVXSADSANSAW4NEXHN55SYQ5YP7HKKZDP3D43IDHZFLTA7) you can find a full operations history for the `GCPV...FLTA7` account. If you have a question regarding some specific operation, please clarify. I'm afraid it will be impossible to find "some coins" payment that has been made "some months ago".

**Comment by dpsdom** [comment]
hello 
Thanks for the  response, but it means nothing to me . I have all the transition details and the coins are GCPVD53G4KMVXSADSANSAW4NEXHN55SYQ5YP7HKKZDP3D43IDHZFLTA7  and on the block chain . They, however, did not end up in my wallet as I did not put the message it .   what can I do

**Comment by orbitlens** [comment]
Sorry, but I don't understand what exactly do you want. If you sent your coins to the exchange, contact them and provide transaction details, so they could deposit your transaction manually.
