### ISSUE TITLE
Fee Source Account is an amount not an account

### ISSUE THREAD

**Issue by tyvdh** [orbitlens/stellar-expert-explorer#202]
![Screen Shot 2020-06-09 at 10 43 53 AM](https://user-images.githubusercontent.com/4383610/84162601-9142f480-aa3e-11ea-8187-0d2cb7e909af.png)

https://stellar.expert/explorer/testnet/ledger/652988

**Comment by orbitlens** [comment]
Fixed in v0.13.7
