### ISSUE TITLE
transfer not received

### ISSUE THREAD

**Issue by Rafaelg11** [orbitlens/stellar-expert-explorer#203]
Hello, last June the 5th I made a transfer from Genbit exchange to Beldex exchange, turns out that" 
this transfer is listed at Stellar as "sent" but it isn´t there at my account at Beldex, could you please check this transfer? thanks a million- Rafael
Transaction 6060dc67b96a41b0047d540f20d688e6772bff7430035d5cbc74c50f726a2f65

**Comment by orbitlens** [comment]
All Stellar transactions are final and irreversible. Your particular transaction was successful, so funds 100% were received by the destination account. 

Check whether GDQ54YQUAWJAOBLZ6T3LPPHPJXPZ3WOBAP746J6STOGFPJ3E6SVVETVZ (the account that received funds) really belongs to Beldex. Visit deposit page there and check the deposit address.

If yes, you need to contact their support and provide transaction id.
