### ISSUE TITLE
failed transaction

### ISSUE THREAD

**Issue by roddy17** [orbitlens/stellar-expert-explorer#204]
Hello;
I made a transaction earlier today from my external nano s wallet to cryprto.com acct but the account-wallet there is not able as of yet to take XLM! Wish there was a pop up note preventing a transfer...I have the transaction ID, time etc...I sent - orbit.lens@gmail.com who is listed at bottom of Stellar Expert transaction page a note earlier.
Please advise...
Rodd
roddcruikshank@gmail.com

**Comment by roddy17** [comment]
Hello?

**Comment by orbitlens** [comment]
Answered via email
