### ISSUE TITLE
xlm withdrawal not showing 

### ISSUE THREAD

**Issue by kimcheeman85** [orbitlens/stellar-expert-explorer#208]
I did a withdrawal from binance.us to my ledger. 
The transaction was successful however the amount is not showing up on my ledger account. 

I've checked the transaction on payment locator on stellar expert and can't seem to find anything wrong however its already been 2 full days and I still do not see it on my balance. 

Please help. 

e987209afa40a072df69f048cd28f29886e7f917eb6dbde5b0f135db64045da6

**Comment by orbitlens** [comment]
Funds were transferred to the account GCXTF3I3LDOVDT7QJZNWNCXLVYXETU7CLIZ6Q263AST4XXHDE2LBHMYO. If it's your Ledger account, don't worry your funds are there.
