### ISSUE TITLE
Withdraw amount not received,   

### ISSUE THREAD

**Issue by HakimBoss** [orbitlens/stellar-expert-explorer#211]
A long time ago withdraw, but my withdraw address not received amount,
Address:   
GBJNV2MQA7M5GNBRDFW46JLXIN7ZLYVVM4UW4CWDZO4KZKXIXCRYHMH2
![Screenshot_2020-07-10-23-12-17-397_com chrome beta](https://user-images.githubusercontent.com/58031922/87181236-c2e00180-c303-11ea-8194-ba67a4da7f05.jpg)
![Screenshot_2020-07-10-23-10-45-517_com chrome beta](https://user-images.githubusercontent.com/58031922/87181239-c6738880-c303-11ea-81e7-9695eec893f1.jpg)

**Comment by orbitlens** [comment]
As I can see from your screenshot, you haven't filled the memo field while depositing funds to Binance.
You need to contact their support team and provide this transaction id. They can process your deposit manually.
