### ISSUE TITLE
Trezor updated and my wallet vanished. I can view the wallet but how can i reach it?

### ISSUE THREAD

**Issue by R31LLY** [orbitlens/stellar-expert-explorer#212]
My trezor T updated and my xlm wallet vanished. I have a new one that needs credit to use it. I refuse to do it as I have a wallet, that I can view on the blockchain.

I've lost 50k xlm I have my keys etc but how can I access my wallet?

**Comment by orbitlens** [comment]
If you have the backup of your seed phrase, check [Trezor emergency recovery guide](https://wiki.trezor.io/User_manual:Emergency_situations).

**Comment by R31LLY** [comment]
That failed. What next
________________________________

**Comment by orbitlens** [comment]
Sorry to say that, but without a seed phrase backup your funds are lost forever. The network is decentralized and it means that nobody except the owner can access funds stored on the account. Neither government, developers, or node admins.

**Comment by R31LLY** [comment]
I have them but that address has vanished
________________________________
