### ISSUE TITLE
Unable to search using asset code

### ISSUE THREAD

**Issue by JakeUrban** [orbitlens/stellar-expert-explorer#216]
When I type "SRT" into the search bar on testnet there are no results. Same for other assets that exist on the network. I'm fairly confident I used to be able to do this.

**Comment by orbitlens** [comment]
Due to the test network reset (which occurred yesterday) we recreated the database and it took some time to recreate full-text search indexes. It was a temporary maintenance issue. Now everything is back to normal. 

Thanks for the heads up.
