### ISSUE TITLE
The API return does not have memo information, it is possible?

### ISSUE THREAD

**Issue by RASTecnoTI** [orbitlens/stellar-expert-explorer#217]
Hi

I have using the API but I see that return does not have the memo information on json code. It is possible add? Anybody knows?

**Comment by orbitlens** [comment]
Sure, we'll add memo to the returned operations data.
The feature seems fairly straightforward, so it should be ready next week.

**Comment by RASTecnoTI** [comment]
Hi
Great to ear it!!! This information on API return data will help us much!

**Comment by orbitlens** [comment]
Sorry, I completely forgot to circle back to you. We have added the memo information two releases ago.
Check output example [here](https://api.stellar.expert/explorer/public/payments?limit=5&memo=1).
