### ISSUE TITLE
XLM Widrawal FROM LEDGER X To BINANCE

### ISSUE THREAD

**Issue by bizzcom2** [orbitlens/stellar-expert-explorer#219]
Hi, 
I have transferred XLM Tokens from my ledger X wallet to Binance XLM Wallet, My tokens are out but It has not delivered to my Binance account, One thing I forgot here, I have not mentioned Memo ID at the time of withdrawal, So please help me to get back my xlm tokens. What steps I need to take to get those tokens back in my wallet.

**Comment by orbitlens** [comment]
https://www.binance.com/en/support/faq/115003798632-Summary-of-Incorrect-Deposit
