### ISSUE TITLE
CoinBase or stellar

### ISSUE THREAD

**Issue by fightingmonsters1969** [orbitlens/stellar-expert-explorer#223]
Trying to figure out is it is normal to wait 24 hours for transfer from lobstr to coin base when the stellar system  says the transaction successful and complete both time now problems and I know im doing it right

**Comment by fightingmonsters1969** [comment]
And what is up two days three days and only robot responses from the company s does anyone use real people for issues to handle clients  anymore I cannot bring my clients into this they would hang me if their money got held up for says at a time Now this si from stellar lobstr to stellar term to coinbase

**Comment by fightingmonsters1969** [comment]
Status:Successful
Ledger:31369726

**Comment by orbitlens** [comment]
I guess [this is your payment](https://stellar.expert/explorer/public/tx/5175a68917d4ce706a67c9a5fa4afc212ff6bbcf2e662670faf75d25260ae056)? 

If so, you added incorrect memo to the transaction. Coinbase deposit instructions contain clear message that the memo field is required and your funds will be lost if you forget to attach the memo or provide some incorrect value. 

Now, only Coinbase support can process your deposit manually. You need to contact them and provide the link to the transaction (see above).

**Comment by fightingmonsters1969** [comment]
Yes I did i figured it out after i complained but they really do need
better service i spoke with them on twitter they said they would check it
out and get back to me but i sent today eth there correct from my metamask
wallet and now that is not showing up it is really frustration haven no
human response
