### ISSUE TITLE
List of payments is not listed

### ISSUE THREAD

**Issue by RASTecnoTI** [orbitlens/stellar-expert-explorer#224]
Hi
I am seeing on blockchain balance is different of list of payments. Take a look on this account where I have one balance value and on payments list I don´t have the transaction listed.

https://stellar.expert/explorer/public/account/GDTERNXF6WEJLQA3IT3YEFUPI2TAM2LFEFPFNWODOCAPVSVGUSGAWMQ2?filter=payments&order=desc

**Comment by orbitlens** [comment]
Hello, we had issues with Horizon server, so StellarExpert history sometimes lags behind the ledger. The release we deployed today should fix this.
Thanks for the heads up.
