### ISSUE TITLE
Search transaction memos

### ISSUE THREAD

**Issue by cosinusx** [orbitlens/stellar-expert-explorer#237]
Hi,

the [Payment locator](https://stellar.expert/explorer/public/payment-locator) can be used to scan the blockchain for a memo that was used for the transaction.
However, Stellar allows different [types of memos](https://www.stellar.org/developers/guides/concepts/transactions.html). Stellar.expert does only search the "MEMO_TEXT" type. Is there a way to search for transactions with memos of the other types, especially for "MEMO_HASH"?

**Comment by orbitlens** [comment]
Hey, sorry for the long response. 

You can search by memo type `hash` or `return` using base64-encoded binary data. For example, check https://stellar.expert/explorer/public/payment-locator?memo=nkgUb7M8zlY75p%2BuHjM6TmSIGpgAAAAAAAAAAAAAAAA%3D
