### ISSUE TITLE
Missing Stellar Lumens - cannot find where crypto went at destination address

### ISSUE THREAD

**Issue by keels77** [orbitlens/stellar-expert-explorer#239]
![image](https://user-images.githubusercontent.com/4728603/99294962-cb48cb80-2812-11eb-9cfe-bd29f8804702.png)

**Comment by orbitlens** [comment]
Please provide additional information. It's unclear what are you asking.

**Comment by keels77** [comment]
I sent stellar lumens from my coinbase account to nexo account but i cannot find in nexo account

**Comment by keels77** [comment]
What other information do you need me to provide . Please advise.

**Comment by orbitlens** [comment]
The transaction shows that you didn't provide a memo. This field is required to deposit funds to your custodial account. 

You need to contact Nexo support, and provide the link to your transaction (the page on the screenshot you sent).
They can process your deposit manually.
