### ISSUE TITLE
xlm did not transfer from coinbase to bitrue

### ISSUE THREAD

**Issue by Kazmania1969** [orbitlens/stellar-expert-explorer#241]
[https://stellar.expert/explorer/public/tx/d5571340d3f881441c828c731495947cfaebeeb953b57d5fb9135fec57fd4a9f](url)[xlm transaction](https://user-images.githubusercontent.com/74586480/99355430-e1d04080-286d-11eb-91e7-453c40d75c3f.jpeg)

I sent xlm from my coinbase account to bitrue.  the address for my bitrue account is corect, but the memo field was a digit off.  it should have been 19695059, but was entered as 19695058.  is my xlm gone or can this be recovered?

Thank you!

**Comment by orbitlens** [comment]
It's impossible to change the memo once the transaction is submitted.

You need to contact the Bitrue support team and provide a link to your transaction. They can process your deposit manually.
