### ISSUE TITLE
Scam mirror site imitating  Stellar - with a staking scam that empties your account - nasty sting!

### ISSUE THREAD

**Issue by miscabc** [orbitlens/stellar-expert-explorer#243]
For Alert, reposting and action:-

There is a scam mirror site   stellar.org.gl
Valid site is  stellar.org
Scam site promotes a Stellar Community Staking Reward system, then empties your account.
I can see the 'new' account but of course I now don't have access to it.
Nasty loss - nasty sting.
Be aware everyone - be safe everyone.

**Comment by orbitlens** [comment]
Thanks for the report. I sent this information to other community members as well.
