### ISSUE TITLE
sent xlm with no memo, can I get it back 

### ISSUE THREAD

**Issue by spurgexlm** [orbitlens/stellar-expert-explorer#244]
transaction id 8f28f02bd07713db927aa14652dd7f1f103618019dfb0ab26991571a6ed1ca2d

**Comment by jaxs043** [comment]
Me too

**Comment by jaxs043** [comment]
How do we get our funds back please.help

**Comment by orbitlens** [comment]
It looks like you forgot to add the memo to the transaction. Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the destination exchange support team and provide a link to your transaction. They can process your deposit manually.
