### ISSUE TITLE
I put the wrong memo tag how to recover my con back

### ISSUE THREAD

**Issue by sahiramsiyag007** [orbitlens/stellar-expert-explorer#246]
Hello, I transferred 836.65 xlm from a exchange to other but I put the wrong memo tag. 
My withdrawal address- GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A

Memo-1022568865 (but I put 1022568865bi )
Transection id- 63d483f11f4c2bdbc3f9970b5add21436133fc438a01bb1c9727ed cfd937db2f

Screen shot attached
Please help me😢🙏
![Screenshot_2020-11-24-17-36-39-729_com wrx wazirx](https://user-images.githubusercontent.com/74980760/100127156-d51e9e80-2ea4-11eb-86ab-893653220ab2.jpg)

**Comment by orbitlens** [comment]
You need to contact Binance support team and provide a link to your transaction. They can process your deposit manually.
https://www.binance.com/en/support/faq/115003798632-Summary-of-Incorrect-Deposit
