### ISSUE TITLE
Never received my stellar 

### ISSUE THREAD

**Issue by Keem24** [orbitlens/stellar-expert-explorer#249]
I sent my XLM to an exchange an it disappeared. The mystery just makes me wanna leave this coin alone all together an convert my position

**Comment by orbitlens** [comment]
Maybe you forgot to add the memo to the transaction. Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the destination exchange support team and provide a link to your transaction. They can check everything and process your deposit manually if something went wrong.
