### ISSUE TITLE
Never recieved deposit

### ISSUE THREAD

**Issue by fardinho21** [orbitlens/stellar-expert-explorer#250]
The operation ID is 125530924715614209
I sent from my online stellar wallet to a coinbase account. This transaction happened on 4/17/2020  and I just noticed  that I am missing funds.  Please help.

**Comment by orbitlens** [comment]
You need to contact Coinbase support team and provide them this transaction link: https://stellar.expert/explorer/public/tx/125530924715614208#125530924715614209
