### ISSUE TITLE
NO ME LLEGO NINGUNO DE LOS DEPOSITOS A MI WALLET DE XLM 

### ISSUE THREAD

**Issue by mgarciaanarko** [orbitlens/stellar-expert-explorer#251]
https://stellar.expert/explorer/public/account/GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A?order=desc      AQUI DEJO EL LINK PARA QUE LO PUEDAN VER , ME GUSTARIA SABER QUE MAS NECESITAN PARA PODER RESOLVER EL PROBLEMA ,EN LA CADENA DE BLOCKES ESTAN TODAS LAS TRASFERENCIAS COMFIRMADAS Y A MI ID NO LLEGO NADA QUE TENGO QUE HACER , YA HABLE CON EL PROBEDOR DE MI ID QUE ES BINANCE Y ME DIJERON QUE ES PROBLEMA DE SU BLOCKCHAIN

**Comment by orbitlens** [comment]
You need to contact Binance support team. We can't help you with your problem.
