### ISSUE TITLE
Missing transactions on blockchain

### ISSUE THREAD

**Issue by RASTecnoTI** [orbitlens/stellar-expert-explorer#252]
Hi
I have one transaction completed but is not listed on blockchain

https://stellar.expert/explorer/public/tx/503408fa8f07314b43835b5c4ab5f7eca7e41b90524c382b279cf23ad29ea931

This is the destination address, but is not updated since 2 days ago.
https://stellar.expert/explorer/public/account/GAT4V4WPPOKVILJYBJAQWFC6QJDEAXUISJTJXCCIBCH2WROC6GVF3BWS?order=desc

**Comment by aolieman** [comment]
I was just about to report the same. Can give examples of at least two other accounts that had recent transactions not visible in stellar-expert. Let me know if that would help, but I guess there is an overall ingestion problem.

**Comment by RASTecnoTI** [comment]
Yes, sure.
Take a look on this asset TREEP. The last transaction was yesterday and I sent and other people sent TREEPs but is not listed.

https://stellar.expert/explorer/public/asset/TREEP-GAVBWV24PZ6POVQGQO5UEWGO3TO7ERYXRFFI6V5VH3BMTPDZOHVOFA3G-2?order=desc

**Comment by RASTecnoTI** [comment]
The last one was this transaction:
https://stellar.expert/explorer/public/tx/ae8900f99ac521418d147c80fa3d171402c9ba0fd2ab56c3ab137b9fb3837698

After this I have more 3 receiving TREEPs
https://stellar.expert/explorer/public/tx/071b3152353f86b75bf5ee27daca1414bad158f4ea9061a318cb6318b2290be2
https://stellar.expert/explorer/public/tx/ca2dc8f1bb4edfb1b90a9ba584aa94ef7250c04d90174a25b52a98fa28fee3b6
https://stellar.expert/explorer/public/tx/503408fa8f07314b43835b5c4ab5f7eca7e41b90524c382b279cf23ad29ea931

**Comment by orbitlens** [comment]
Thanks for the heads up. The problem is caused by the degraded performance of our ingestion engine due to hardware issues (some db indexes don't feet in 256GB RAM of our servers anymore).

We are working on a fix right now. Estimated time - 1 hour.

**Comment by orbitlens** [comment]
Fixed. Sorry for the delay. The process took much longer than originally estimated.
