### ISSUE TITLE
Please Help! Stellar website "reloaded itself", created an additional account, and I lost 15,000 XLM

### ISSUE THREAD

**Issue by abilenesuperhero** [orbitlens/stellar-expert-explorer#253]
Greetings, from this lonely pit of despair.

After learning about the recent staking marathon taking place for XLM holders, I created an Account ID on the Stellar website and transferred an initial 500 XLM from my Coinbase account to ensure the transaction posted properly (which it did). After verifying this, I sent the remaining balance of my XLM holdings (14,500) to my public address, just as I did the first time, in an effort to take full-advantage of the staking reward potential with all of my holdings. After making the transfer, I opened my Stellar Account ID page and it showed that the remaining 14.5k had been successfully transferred, but for some reason the page prompted a notification stating (roughly) that "there was an error processing your transaction" and "the source of your transaction could not be verified" then prompted me to essentially "refresh/reload" to verify the transaction. I didn't know why there would be any additional transaction aside from the second (14.5k XLM) transfer, and I figured there may have been something about sending two subsequent transactions so closely together from/to the same addresses, so I followed the prompt and reloaded it. The webpage loaded for several minutes and then, suddenly, all but 1.9999800 XLM were **gone**.  I have no idea why or how it happened, and I have even less of an idea of what to do. I read through dozens of resources but found few answers. Through Stellar.Expert, I found the public transaction details, which I've listed links to below. Attached is a screenshot of my SDF Account Viewer page, listing the transactions at the bottom. I also have the operation details listed on my SDF Account Viewer page, which I can provide for anyone who can help. Noted in the Operations section on the Stellar.Expert Transaction Details, it says that, "GCYM....D5ID [My Public Key] created account GBT7...T37V with starting balance 14,998 XLM" which I **did not** do! It seems as though the website created another additional account, while I was somehow logged into my initial account. The _only_ account I created was the initial one (through SDF) earlier that evening, and the _only_ intentional transfers I made were from my Coinbase wallet, to the automatically-generated-address SDF wallet. I have the secret key and can access the account I initially created, but (obviously) not the second account that was somehow mysteriously created. Currently, all 14,998 XLM are still in the secondary account, and haven't been transferred to any other account, which indicates a "mistake" rather than an intentional hack or scam by/from some other party. Additionally, every step of the entire process was carried out within the SDF website, and no additional third-party websites, services, or exchanges were involved. 

Any help would be greatly appreciated. Like I said, I'm at a loss and I don't really know what to do or where to find help. I've listed links including information regarding the transaction(s) in question below. Please let me know if there's anything else I could provide that might help resolve the issue.

Respectfully,
-Ryan

 
My Stellar Public Key is: 
GCYM7L25J2PUBFO4SRGTNWPJBCPR3VFA67YG4E3CYY5ZZ6CRCZ5UD5ID

The Stellar Public Key for the Unknown account that the 14,998 XLM were sent to is:
GBT7RPGON5A4NIKPNNHO5J2ZRR6QXSP3D43IOHXANAOBI622USYJT37V 

My Coinbase wallet address that all 15,000 XLM were sent from is:
GDQP2KPQGKIHYJGXNUIYOMHARUARCA7DJT5FO2FFOOKY3B2WSQHG4W37
XLM Memo ID: 3745906794

Note: I did not use a Memo for either of the transactions from my Coinbase wallet to my newly created Stellar Wallet as it was optional and I was simply sending it to myself.

Here's the account I created on the SDF website to transfer holdings into to enroll in staking rewards:
https://stellar.expert/explorer/public/account/GCYM7L25J2PUBFO4SRGTNWPJBCPR3VFA67YG4E3CYY5ZZ6CRCZ5UD5ID?order=desc
 
Here are the transaction details regarding the transferral of 14,998 XLM from my SDF wallet to the unknown account:
https://stellar.expert/explorer/public/tx/139913670678487040#139913670678487041

Here are the account details of the address that was somehow transferred 14,998 XLM from my intentionally created account, into:
https://stellar.expert/explorer/public/account/GBT7RPGON5A4NIKPNNHO5J2ZRR6QXSP3D43IOHXANAOBI622USYJT37V?order=desc

Here are the Operation details provided at the bottom of my SDF Account Viewer page for the transaction in question:
https://horizon.stellar.org/operations/139913670678487041

**Comment by orbitlens** [comment]
Hello
There is no stacking on Stellar. Looks like you send your money to scammers. Check official [Stellar security guide](https://www.stellar.org/blog/stellar-security-guide-protect-scammers).

We marked the account you mentioned as malicious. https://stellar.expert/explorer/public/account/GBT7RPGON5A4NIKPNNHO5J2ZRR6QXSP3D43IOHXANAOBI622USYJT37V

I'm afraid we can't do anything else at the moment. Transactions on the ledger are irreversible, so nobody can get your funds back. The best chance you have is to wait until money is transferred to a custodial exchange and then contact a local law enforcement agency.
