### ISSUE TITLE
Scam address => GBEUYU6BMXN7UBHKNKXRB6RS44UJJSUTR5YYVNZQZ27BNUSRRT5OYMDE

### ISSUE THREAD

**Issue by tc71** [orbitlens/stellar-expert-explorer#254]
Can I recover a really large amt of my XLM that was scammed by my Ledger Nano created a wallet address from its seed?
1) I subscribe to Stellar newsletter for past 2 yrs & got a phishing newsletter. I checked the cert & it was good BUT I missed the " .gl " in the URL, see => https://accountviewer.stellar.org.gl/#!/
2) my Ledger wallet address is => https://stellar.expert/explorer/public/account/GBA32D3V57HGUC7GOCWK2WW74EV5CVBF6UI42OKUVTP3CZGDLSZU4MTY?order=desc
3) the scam address that was created from my address above => https://stellar.expert/explorer/public/account/GBEUYU6BMXN7UBHKNKXRB6RS44UJJSUTR5YYVNZQZ27BNUSRRT5OYMDE?order=desc

**Comment by tc71** [comment]
Please help me in any way......Thanks!
~ Tony Satocci

**Comment by tc71** [comment]
CORRECTION=> Scam wallet generated from my wallet seed -
https://stellar.expert/explorer/public/account/GBEUYU6BMXN7UBHKNKXRB6RS44UJJSUTR5YYVNZQZ27BNUSRRT5OYMDE

**Comment by tc71** [comment]
If my Ledger XLM wallet created the address *BELOW* => is there a way for my private key unlock the wallet ?
![scam-wallet](https://user-images.githubusercontent.com/75206813/100610139-27185780-32dd-11eb-8da8-febc70e25e07.png)

https://stellar.expert/explorer/public/account/GBEUYU6BMXN7UBHKNKXRB6RS44UJJSUTR5YYVNZQZ27BNUSRRT5OYMDE

**Comment by orbitlens** [comment]
Hello
Sorry to hear that. We marked the account you mentioned as malicious. https://stellar.expert/explorer/public/account/GBEUYU6BMXN7UBHKNKXRB6RS44UJJSUTR5YYVNZQZ27BNUSRRT5OYMDE

I'm afraid we can't do anything else at the moment. Transactions on the ledger are irreversible, so nobody can't get your funds back. The best chance you have is to wait until money is transferred to a custodial exchange and then contact a local law enforcement agency.

**Comment by abdomi** [comment]
@tc71 please contact me on Keybase, https://slack.stellar.org
