### ISSUE TITLE
500.00$ worth without destination tag. 

### ISSUE THREAD

**Issue by theLordSatan** [orbitlens/stellar-expert-explorer#255]
Sent 500.00$ worth of stellar and never reached destination wallet without destination tag.. how long will I get my stellar back ??? This is nuts

**Comment by orbitlens** [comment]
Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the destination wallet support team and provide a link to your transaction. They can process your deposit manually.
