### ISSUE TITLE
Transaction Error

### ISSUE THREAD

**Issue by Deontre11** [orbitlens/stellar-expert-explorer#256]
I recently traded xlm from my ledger wallet to my coinbase wallet. However the transaction says that it has been confirmed however when I look into my coinbase wallet my money is not in there along with my shares. Can you please help me!?

**Comment by Silvina13** [comment]
Same thing just happened to me.

**Comment by orbitlens** [comment]
It looks like you forgot to add the memo to the transaction. Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact Coinbase support team and provide a link to your transaction. They can process your deposit manually.

**Comment by Deontre11** [comment]
Thank you.
