### ISSUE TITLE
XLM transfer not showing up in Coinbase from Ledger

### ISSUE THREAD

**Issue by Silvina13** [orbitlens/stellar-expert-explorer#257]
341.99999 XLM transferred to Coinbase and it's showing transaction complete but not in Coinbase account.

**Comment by orbitlens** [comment]
It looks like you forgot to add the memo to the transaction. Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact Coinabse support team and provide a link to your transaction. They can process your deposit manually.
