### ISSUE TITLE
Help with transaction

### ISSUE THREAD

**Issue by chaka10** [orbitlens/stellar-expert-explorer#258]
I look forward to any help that you can provide to recover my funds. If you look at the account created by my wallet the funds are still there. Please I am going through some really tough times due to losing my job in march at the start of the Pandemic. Attached are screen shots of date and time of the scam transaction. Also I looked with viewer yesterday 12/3/2020 and looks as funds are still in account created. Today is my birthday and I thought I would reach out to Stellar preying for a solution to help me get my funds back. I tried when this first happened reaching out on the blog and saw the same thing happen to a couple of XLM holders in the same week.  Well my Lumens did not move for years waiting for another bull market. Please HELP there has to be a way to get these coins back, being as they have not moved in years except from my account into the scam account that My wallet set up some how according to operation number 133886521597046785 I know this may not seem like a lot of money to you but when your about to be homeless and disabled this could possibly give me a start to save my family's life. I am thanking you in advance for helping me with a solution to this very unfortunate situation.  
Kindest Regards,
Gary

<i

Screen Shot 2020-08-18 at 1.15.01 PM
<img width="1575" alt="Screen Shot 2020-08-18 at 1 15 01 PM" src="https://user-images.githubusercontent.com/75452165/101204357-

**Comment by orbitlens** [comment]
Sorry to say, but it's not possible to reverse a transaction. We have added the destination address to the blacklist. That's pretty much everything we can do for you. We are in the process of the negotiations with custodial exchanges to provide a mechanism of blocking stolen funds once scammers try to exchange them for fiat money.
