### ISSUE TITLE
Wrong information MEMO on API results

### ISSUE THREAD

**Issue by RASTecnoTI** [orbitlens/stellar-expert-explorer#259]
Hi
The API is getting the memo information wrong like this:

https://api.stellar.expert/api/explorer/public/payments?account=GDDTZNNH7BXXWVKVM4VMYDIYGHJ7SWEB3QQ3IJPIVHCSNTL7A7GDITRG&limit=200&order=desc

{"id":"141580534601093121","paging_token":"141580534601093121","optype":1,**"memo":14427229**,"ledger":32964287,"tx_id":"141580534601093120","ts":"2020-12-07T12:42:57.000Z","from":"GDQ54YQUAWJAOBLZ6T3LPPHPJXPZ3WOBAP746J6STOGFPJ3E6SVVETVZ","to":"GDDTZNNH7BXXWVKVM4VMYDIYGHJ7SWEB3QQ3IJPIVHCSNTL7A7GDITRG","asset":"TREEP-GAVBWV24PZ6POVQGQO5UEWGO3TO7ERYXRFFI6V5VH3BMTPDZOHVOFA3G-2","amount":"10000","source_asset":"TREEP-GAVBWV24PZ6POVQGQO5UEWGO3TO7ERYXRFFI6V5VH3BMTPDZOHVOFA3G-2","source_amount":"10000"}

And the graphic interface the memo is ok
https://stellar.expert/explorer/public/tx/141580534601093120#141580534601093121

![image](https://user-images.githubusercontent.com/64599826/101704442-8572d200-3a63-11eb-8305-7ff4a43e9330.png)

**Comment by orbitlens** [comment]
Fixed.
Sorry. Don't know how this happened. We really tested this like 5 days ago.

**Comment by RASTecnoTI** [comment]
I want to say thank you for fast fix!
