### ISSUE TITLE
please add the ability to download the data behind the charts

### ISSUE THREAD

**Issue by christianrudder** [orbitlens/stellar-expert-explorer#26]
Please add the ability to download the data behind the charts as a csv.

For example, here:

https://stellar.expert/explorer/asset/PHP-GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP

and here

https://stellar.expert/explorer/asset/EURT-GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S

For "price and volume" "supply and accounts" and "asset flow" I really need the underlying data to do the analysis I need to do.

**Comment by orbitlens** [comment]
There are no plans to implement the export functionality so far. You can get the data in JSON format, just open the following links in a browser. 

- Trades history (`/api/asset/{code}-{issuer}/price-history`)
https://api.stellar.expert/api/asset/PHP-GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP/price-history
- Supply and accounts (`/api/asset/{code}-{issuer}/cumulative/supply-and-trustlines`)
https://api.stellar.expert/api/asset/PHP-GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP/cumulative/supply-and-trustlines
- Transfers and trades (`/api/asset/{code}-{issuer}/cumulative/transfers-and-trades`)
https://api.stellar.expert/api/asset/PHP-GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP/cumulative/transfers-and-trades

The same for EURT, all you need is to replace `{code}-{issuer}` part with the asset code and issuer from the asset page URL.

**Comment by christianrudder** [comment]
Okay great. Thank you.
