### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by Ezzyp123** [orbitlens/stellar-expert-explorer#261]
Hi, I sent xlm from Stellar app to coinbase but it never showed up despite me punching int he right address...can you help? I have sequence number, thanks!

**Comment by del359es** [comment]
Hello, I sent XLM to Coinbase and they were never received. how can I get them back? Operation 141064966726942721 - Payment

**Comment by del359es** [comment]
Hello again, these XLM were not deposited either. Operation 141064966726942721 - Payment

**Comment by Ezzyp123** [comment]
Is someone supposed to get back to me or do I just wait

**Comment by del359es** [comment]
Hello, I am responding to your question. What do I do now to work on getting my transaction completed?
    On Thursday, December 17, 2020, 12:50:48 PM EST, Ezzyp123 <notifications@github.com> wrote:  
 
 


Is someone supposed to get back to me or do I just wait

**Comment by orbitlens** [comment]
It looks like you forgot to add the memo to the transaction. Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the destination exchange support team and provide a link to your transaction. They can process your deposit manually.

If it's not the case, provide your transaction id and I'll take a look.
