### ISSUE TITLE
Hello, I sent XLM to Coinbase and they were never received. how can I get them back?  The transaction was done on November 29, 2020

### ISSUE THREAD

**Issue by del359es** [orbitlens/stellar-expert-explorer#262]
Hello, I sent XLM to Coinbase and they were never received. how can I get them back?  The transaction was done on November 29, 2020

_Originally posted by @del359es in https://github.com/orbitlens/stellar-expert-explorer/issues/261#issuecomment-743933278_

**Comment by orbitlens** [comment]
Maybe you forgot to add the memo to the transaction. Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the Coinbase support team and provide a link to your transaction. They can process your deposit manually.
