### ISSUE TITLE
XLM

### ISSUE THREAD

**Issue by unamatika** [orbitlens/stellar-expert-explorer#264]
Dobrý den, poslal jsem na penezenku bez Tagu je možná rada, jak dostat platbu zpět?
Děkuji

**Comment by orbitlens** [comment]
Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the destination exchange support team and provide a link to your transaction. They probably can process your deposit manually.

**Comment by unamatika** [comment]
Dobry den,
Děkuji. Jak zjistím s čísla peněženky kam bylo odesláno,
Komu patří, abych ho mohl kontaktovat?

*GAWPTHY6233GRWZZ7JXDMVXDUDCVQVVQ2SXCSTG3R3CNP5LQPDAHNBKL*

*Děkuji za pomoc*
*Filio*

ne 20. 12. 2020 v 21:39 odesílatel orbitlens <notifications@github.com>
napsal:

**Comment by orbitlens** [comment]
Contact the destination exchange. If you sent money to Bitfinex, then contact their support.
