### ISSUE TITLE
Xlm had to memo

### ISSUE THREAD

**Issue by danschwa88** [orbitlens/stellar-expert-explorer#266]
I did not put in memo but receiver did not get XLM. I sent from coinbase 575.80 and it says pending still. Coinbase said reach out here. Please help! Times are tough!

**Comment by danschwa88** [comment]
Had no memo. Everything else was correct we have the address is confirmed from the recipient that everything is right.

**Comment by orbitlens** [comment]
Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the destination exchange support team and provide a link to your transaction. They can process your deposit manually. We can't help you with this matter, as we don't hold your funds (or any funds at all).
