### ISSUE TITLE
i fucked up

### ISSUE THREAD

**Issue by philabsurd** [orbitlens/stellar-expert-explorer#267]
is there a way to reverse a transaction?

**Comment by hoelderlin2368** [comment]
Same here. Wish Stellar would allow to block fraudulent accounts and freeze the assets.

**Comment by orbitlens** [comment]
Hey,
Sorry for the long response. We are overwhelmed with similar support requests.

Several days in a row we've been working heads down to prevent further attack spread.
Here is a short post about what we are doing right now to prevent such attacks and help people recover their funds:
https://www.reddit.com/r/Stellar/comments/kij4hb/proactive_blocking_of_phishing_websites_with/

Please provide transaction details. I'll to review your transactions history and mark all attackers' accounts as #malicious. You'll need to contact your local law enforcement agency to fill up an official claim. I'll help you to track transactions all the way up to exchanges when scammers try to cash out funds. Without an official request from police exchanges won't share any details and won't block the accounts. This way, you have a decent chance to get your money back.

I'm afraid, this is all I can do for you at the moment.

**Comment by philabsurd** [comment]
I emailed you directly with all the details several days ago, 12-17-20, including transaction number and report I filed with ic3.

**Comment by philabsurd** [comment]
i got a response from you but i had already sent the info
phil absurd <philabsurd@gmail.com>
[image: Attachments]Thu, Dec 17, 2:46 PM (7 days ago)


to orbit.lens
