### ISSUE TITLE
Hi I thought I could stake lumens and sent them to this address from my ledger wallet

### ISSUE THREAD

**Issue by BDSabino** [orbitlens/stellar-expert-explorer#268]
GAT4EU52F3W5YOKEI647OAV7Q24DQKZZY2AZDADTW4DQSEN3FPSRIFON
I do not know how to access these lumens, or if they are staked- when they mature what i should do to unstake. I am very nervous. Please help!

**Comment by Thescrob** [comment]
hi
i got same issue as you with staking  lumens on the albedo wallet.
it created a new account and i cant manage it.

**Comment by BDSabino** [comment]
I’m going to contact the SDF, I’ll mention your issue as well!

**Comment by Thescrob** [comment]
ok thats very nice from you. i was looking on everywhere to what to do but
this is really looking bad.
my public key to see transaction :
GAUEGAPHABOR6IERWD5CCYHOIMS5AWGUCNM4KE5IFRKYRFY3MLIRRG2Z

**Comment by Thescrob** [comment]
i really think we just got hard scammed... because of address now seems bad
:
https://stellar.org.mu/blog/introducing-the-stellar-community-staking-competition/

Le sam. 19 déc. 2020 à 20:30, Nicolas Tavakoli <niko.tvk@gmail.com> a
écrit :

**Comment by BDSabino** [comment]
Yup! That sure is the way it seems!

**Comment by BDSabino** [comment]
I created an account in a scam, but I dont believe even the scammer has access. Can I review the records with someone to retrieve my funds even though I dont have the private key. 
And, I may have simply acknowledged a private key with my Ledger Nano S in this process without writing it down. Is there any way to retrieve tis from ledger? 65k lumes are at stake!!!
https://stellar.expert/explorer/public/tx/38f3f094e4d68b2e3afa020538d1805e1196add04275a9fbe5aee5c93af78121

**Comment by Pugg5ter** [comment]
I have a similar issue. Is there a recommended course of action?

**Comment by pavelprokhor** [comment]
I’ve messed up in the same way, what can I do?

**Comment by orinschepp** [comment]
I think we got scammed!! I am working on recovery also!

**Comment by Pugg5ter** [comment]
What are you planning Orinschepp - options seem real limited?

**Comment by BDSabino** [comment]
It’s a shot in the dark. But- I’m going to review all the JSON files or
review the Java scripting for a private seed.

**Comment by orbitlens** [comment]
Hey everyone,
Sorry for the long response. We are overwhelmed with similar support requests.

Several days in a row we've been working heads down to prevent further attack spread.
Here is a short post about what we are doing right now to prevent such attacks and help people recover their funds:
https://www.reddit.com/r/Stellar/comments/kij4hb/proactive_blocking_of_phishing_websites_with/

I'm going to review your transactions history and mark all attackers' accounts as _#malicious_. You'll need to contact your local law enforcement agency to fill up an official claim. I'll help you to track transactions all the way up to exchanges when scammers try to cash out funds. Without an official request from police exchanges won't share any details and won't block the accounts. This way, you have a decent chance to get your money back.

I'm afraid, this is all I can do for you at the moment.

**Comment by BDSabino** [comment]
Wow! You got along further than me with them. I’ll have to consider
contacting them ( and the police) as well.!!! Thx!

**Comment by orbitlens** [comment]
You might also be interested in joining the `scamvictimcollab` group on Keybase to collaborate with other victims of this scammer.

**Comment by BDSabino** [comment]
Cool! I lost touch with my keybase account, but may be able to pull it back
up. Thx again, Very much!!

**Comment by orbitlens** [comment]
All accounts marked as malicious. I'm closing this issue for now. Please move further communication into the Keybase group.
