### ISSUE TITLE
Stellar payment approved but never received 

### ISSUE THREAD

**Issue by kombosski** [orbitlens/stellar-expert-explorer#269]
I supposed to receive 149.9999 lumenst to mine coinbase mobile app lumens adress  and I got notified and checked through till now I don't see even 1 CE in yet transactions been approved 
b3b279946c1afbaac49ac9e0e918e7560b8b92c6503f54ab38b679e7e26b81ca here is a transaction hash

**Comment by xrpyener** [comment]
I have same problem have you sort it ?

**Comment by kombosski** [comment]
Nope buddy had never recive it up until now  8 can 9nl6 see 0000


śr., 23 gru 2020, 19:46 użytkownik xrpyener <notifications@github.com>
napisał:

**Comment by xrpyener** [comment]
How did you receive it sir ?

**Comment by xrpyener** [comment]
Sir can you help me with your experience please what do I have to do ?

**Comment by orbitlens** [comment]
@kombosski please check the expected memo value in the Coinbase deposit instructions of your account. Your transaction shows that you provided memo "2509405964", it should match the deposit memo. In any case, you need to contact Coinbase support, they can deposit your funds manually if something was wrong with the transaction.

**Comment by xrpyener** [comment]
I didn’t put the memo in that’s why it’s lost
