### ISSUE TITLE
Where's my money!!! I transferred to Stellar and now my money is missing!!!!!

### ISSUE THREAD

**Issue by VKS2234** [orbitlens/stellar-expert-explorer#270]
stellarStellarExpertexpert
ASSETSMARKETSNETWORK STATSSERVICES
BLOGLog in with Albedo
Paste an asset code, tx hash, account address, or ledger sequence here
Network public
Transaction 566878a89ee6424bd559a0dda52c2422773d8b4bc8d022377d83b7cf53ac762d

Summary
Status:Successful
Ledger:33117862
Operations:1
Source Account:GCYT7G…56IO56
Sequence Number:140190116248289281

Created:2020-12-17 05:01:30 UTC
Max Fee:0.00001 XLM
Fee Charged:0.00001 XLM
Signatures
GCYT7G…56IO56: tYmL23gfeuLjppXtOuGsqJ/dKCZKBQaD5w/l5qnHgB5ZtYmaTNe54+iFs+bbaDPgXnPAtiVJK/1n9BqaeYm3AQ==
Operations
Hide operations
Operation 142240134203445249 - Payment
GCYT…IO56 transferred 2,598.99999 XLM to [Coinbase Deposits] GDQP…4W37

**Comment by orbitlens** [comment]
The transaction shows that you didn't provide a memo. This field is required to deposit funds to your account. 

You need to contact Coinbase support and provide the link to your transaction (https://stellar.expert/explorer/public/tx/566878a89ee6424bd559a0dda52c2422773d8b4bc8d022377d83b7cf53ac762d).
They can process your deposit manually.
