### ISSUE TITLE
missing XLM

### ISSUE THREAD

**Issue by pavelprokhor** [orbitlens/stellar-expert-explorer#271]
I went to www.stellar.org website then clicked tools and chose Account viewer in the bar. Downloaded the freighter extension and transferred my money into the wallet from my coinbase account. I clicked the button to stake xlm and now i cant seem to get my XLM back can someone help me.

**Comment by xrpyener** [comment]
I got same problem have you got anything back

**Comment by orbitlens** [comment]
Hello, 

Sorry for the long response. We are overwhelmed with similar support requests.
Sorry to say that, but you have been scammed. There is no stacking on Stellar.

Please provide transaction details. I'll review your transactions history and mark all attackers' accounts as #malicious. You'll need to contact your local law enforcement agency to fill up an official claim. I'll help you to track transactions all the way up to exchanges when scammers try to cash out funds. Without an official request from police exchanges won't share any details and won't block the accounts. This way, you have a decent chance to get your money back.

I'm afraid this is all I can do for you at the moment. You can also reach @abdomi on Keybase. He coordinates the joint effort of tracking the scammer.

**Comment by abdomi** [comment]
@pavelprokhor, @xrpyener please join https://slack.stellar.org/

**Comment by xrpyener** [comment]
Is this for real sir how can I be scammed I send to my own account it’s all
I have I have put all my money in xlm now you are saying you been scammed
how I been scammed

**Comment by abdomi** [comment]
@xrpyener can you please post your XLM public address here?

**Comment by orbitlens** [comment]
@xrpyener stop commenting in all threads. I was referring to the @pavelprokhor's problem.

**Comment by xrpyener** [comment]
Sorry I thought you telling me

**Comment by pavelprokhor** [comment]
I created a police report with my city. in Auburn WA 98001. tracking number T20003720. I had 2 transactions the first one is 
e1f1a4bc309c8a917f4ce1a346a26df842c62dc4fefb25fcadb3176ae7f975d8
the second one is 
c9ba8ea501b5b827332167ea88de1c4071ddb2b586ed95869a0aec9d5c9f629c
my wallet number is GBKXBZ3CUDRNJC3ZGO2R5EFJDU37EH2G37254AZOC7NQ7PUMSOTYNU2K. through freighter extension. the wallet my money went to seems to be this one. 
GDR2LARRPK2ZGHVTPWASQDC6KEFFMJYURQS5DJFGEA2FWLVEBBK3OAI5
I'm hoping we can track this guy down and get our money back but I'm loosing hope. Please let me know if you can do anything.     On Thursday, December 24, 2020, 09:56:32 AM PST, xrpyener <notifications@github.com> wrote:  
 
 

Sorry I thought you telling me
