### ISSUE TITLE
lumens gone

### ISSUE THREAD

**Issue by chad369** [orbitlens/stellar-expert-explorer#272]
some assholes stole all my f****** lumens and when I find out I'm going to beat the f****** living hell out of you and break your f****** legs and kill your f****** b**** ass

**Comment by orbitlens** [comment]
Hello, 

Please provide transaction details. I'll review your transactions history and mark all attackers' accounts as #malicious. You'll need to contact your local law enforcement agency to fill up an official claim. I'll help you to track transactions all the way up to exchanges when scammers try to cash out funds. Without an official request from police exchanges won't share any details and won't block the accounts. This way, you have a decent chance to get your money back.

I'm afraid this is all I can do for you at the moment. You can also reach @abdomi on Keybase. He coordinates the joint effort of tracking the scammer.

**Comment by abdomi** [comment]
@chad369, please join https://slack.stellar.org/

**Comment by chad369** [comment]
I can open up more, you can click on it and then it just goes to a lot of
accounts if I find out who it is I'm going to break their knees
