### ISSUE TITLE
Cannot withdraw my Lumens from - https://accountviewer.stellar.org/

### ISSUE THREAD

**Issue by soleri** [orbitlens/stellar-expert-explorer#273]
Hi,

Could someone please advise. I am trying to withdraw my Lumens from "accountviewer.stellar.org. However, it states that "you don't have enough to cover this transaction." Is there a minimum for withdrawals? 

Thank you.

Soleri

**Comment by orinschepp** [comment]
I am having similar issue, trying to find an answer also

**Comment by orbitlens** [comment]
Yes, the minimum account balance is 1XLM plus you need like 0.001XLM to pay for fees. 
If you want reclaim all funds and close the account, check this tool: https://stellar.expert/demolisher/public
