### ISSUE TITLE
Unhandled error occurred

### ISSUE THREAD

**Issue by ubuntuecocenter** [orbitlens/stellar-expert-explorer#276]
"fffff" at https://stellar.expert/explorer/public/asset/UBEC-GDPNB7S3IOM2J6C3NA2QG4TQAUCRZXPJJ4HSCSIKELEH7ORUCX5UB2VN

De@https://stellar.expert/distr/explorer.js:1:147836
Zi@https://stellar.expert/distr/app.js?v=0.15.9:2:521759
Es@https://stellar.expert/distr/app.js?v=0.15.9:2:567809
yu@https://stellar.expert/distr/app.js?v=0.15.9:2:560551
mu@https://stellar.expert/distr/app.js?v=0.15.9:2:560476
su@https://stellar.expert/distr/app.js?v=0.15.9:2:557506
Yo/<@https://stellar.expert/distr/app.js?v=0.15.9:2:509147
t.unstable_runWithPriority@https://stellar.expert/distr/app.js?v=0.15.9:2:584203
Qo@https://stellar.expert/distr/app.js?v=0.15.9:2:508856
Yo@https://stellar.expert/distr/app.js?v=0.15.9:2:509092
Go@https://stellar.expert/distr/app.js?v=0.15.9:2:509027
uu@https://stellar.expert/distr/app.js?v=0.15.9:2:557797
qe@https://stellar.expert/distr/app.js?v=0.15.9:2:44600
ze@https://stellar.expert/distr/app.js?v=0.15.9:2:44183
Be@https://stellar.expert/distr/app.js?v=0.15.9:2:40546
be/<@https://stellar.expert/distr/app.js?v=0.15.9:2:33775
be@https://stellar.expert/distr/app.js?v=0.15.9:2:33846
Ye@https://stellar.expert/distr/app.js?v=0.15.9:2:45507
sync/this.promise<@https://stellar.expert/distr/explorer.js:1:15138

**Comment by orbitlens** [comment]
Sorry about that. The system update we rolled recently gone wrong.
Fixed now.
