### ISSUE TITLE
Lost my xlm from ledger to Coinbase 

### ISSUE THREAD

**Issue by tomananda** [orbitlens/stellar-expert-explorer#278]
I transferred 800+ dollars out of my leisure account but it hasn’t shown up on my Coinbase account after about 18 hours now.

Thank you

**Comment by tomananda** [comment]
Cannot locate XLM sent from ledger to Coinbase

**Comment by burnzcitt** [comment]
I lost money as well. Did they get back with you? How do we transfer xlm off of the ledger. Bunch of bs

**Comment by tomananda** [comment]
Thanks for responding 🙏🏼

**Comment by Zurnx** [comment]
i lost my coins as well.. it’s been a day still haven’t got them yet.. annoying af

**Comment by Zurnx** [comment]
btw don’t swap XLM for other coins either at the moment bcuz i did it a couple days ago and it literally took like 12 hours just to receive my coins..

**Comment by Zurnx** [comment]
btw don’t swap XLM for other coins at the moment bcuz i did it the other day and it took like 12 hours to get them..

**Comment by Zurnx** [comment]
btw don’t swap XLM for other coins at the moment bcuz it took like 12 hours just to get them

**Comment by orbitlens** [comment]
@tomananda Provide transaction id, I'll take a look. 

In like 99% of all cases this happens because people forget to add the memo to the transaction. Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

If that's the case, you need to contact the destination exchange support team and provide a link to your transaction. They can process your deposit manually.

**Comment by tomananda** [comment]
Thank you so much for your help. Here is the transaction number:  22fc2178048b5f729722490770fd17154deb5a78f5bf91cfe8722de9380e401c

**Comment by orbitlens** [comment]
https://stellar.expert/explorer/public/tx/22fc2178048b5f729722490770fd17154deb5a78f5bf91cfe8722de9380e401c

This transaction shows that you haven't provided the mandatory memo. So you need to contact Coinbase support as I mentioned earlier.

**Comment by tomananda** [comment]
Thanks again

**Comment by tlimberiou** [comment]
Has Coinbase ever helped I’ve been waiting since January

**Comment by burnzcitt** [comment]
Yes they were fast about it. I had to send them the hash tag and they
refunded my $
