### ISSUE TITLE
LOBSTR app to stellarguard 

### ISSUE THREAD

**Issue by JordanT094** [orbitlens/stellar-expert-explorer#279]
Hi All,

So I was trying to setup multisig, flicking from the LOBSTR app to the stellarguard website. Really unsure how this happened, I literally blinked and XLM has been sent to stellarguard public key that somehow is different to the one that's on my app for the multi signature and I have no transaction XDR as I didnt get the chance! I didnt enter an amount to send either it just sent a random amount.

Any ideas?

**Comment by orbitlens** [comment]
I can't say what happened since you didn't provide any information about your account, but in any case you'd better contact Stellarguard devs.
