### ISSUE TITLE
Account summary doesn't get updated

### ISSUE THREAD

**Issue by s-a-y** [orbitlens/stellar-expert-explorer#28]
Hey, just noticed something strange, when I'm watching one account, then click another one - Account summary stays the same.

1. 
<img width="1223" alt="screen shot 2018-01-16 at 12 24 49 pm" src="https://user-images.githubusercontent.com/1667781/34967676-9eea14e8-fab8-11e7-922f-9013cec05b73.png">

2. Clicking another account in All Effects -> Details column
<img width="1223" alt="screen shot 2018-01-16 at 12 24 49 pm copy" src="https://user-images.githubusercontent.com/1667781/34967677-a1c7acf2-fab8-11e7-9094-61c4a8c84187.png">

3. 
<img width="1184" alt="screen shot 2018-01-16 at 12 25 04 pm" src="https://user-images.githubusercontent.com/1667781/34967633-654847be-fab8-11e7-8360-c135d96c111b.png">

**Comment by orbitlens** [comment]
Opps. Sometimes React components are not updated on the URL change. 
That's a high priority. 
I'm on it right now.
