### ISSUE TITLE
Missing coins transfered xlm from one wallet to another 

### ISSUE THREAD

**Issue by tjonez** [orbitlens/stellar-expert-explorer#285]
I forgot to add the memo to my transfer to coinbase, is it possible to retrieve?

**Comment by orbitlens** [comment]
Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the Coinbase support team and provide a link to your transaction. They can process your deposit manually.
