### ISSUE TITLE
I Forgot to add memo....is there any way to fix this?

### ISSUE THREAD

**Issue by d1freeman** [orbitlens/stellar-expert-explorer#286]
I exchanged XLM on my nano for BTC .....to send  my wallet....I did not see that I needed a memo.... the transaction is complete but the BTC is not going to my BTC wallet....how can I access/who do I speak to/what do I do?

**Comment by orbitlens** [comment]
Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the destination exchange support team and provide a link to your transaction. They can process your deposit manually.
