### ISSUE TITLE
I transferred my stellar to another coinbase user on 11/29/20 they never received it.. I do have something listed in the memo section

### ISSUE THREAD

**Issue by mrsmelanin** [orbitlens/stellar-expert-explorer#289]
Summary
Status:Successful
Ledger:32840108
Operations:1
Source Account:[Coinbase Withdrawals] GAW62P…52R32P
Sequence Number:137930276255875630

Created:2020-11-29 16:44:21 UTC
Max Fee:0.0015 XLM
Fee Charged:0.00001 XLM
Time Bounds:from 1970-01-01 00:00:00 UTC to 2020-11-29 16:49:16 UTC

Memo (TEXT): your wife

**Comment by orbitlens** [comment]
Every transaction to a custodial exchange requires a valid memo for every deposit. It's impossible to change the memo once the transaction is submitted.

You need to contact the Coinbase support team and provide a link to your transaction. They can process your deposit manually.
