### ISSUE TITLE
Transaction details truncated at 10 operations in "transaction view"

### ISSUE THREAD

**Issue by MonsieurNicolas** [orbitlens/stellar-expert-explorer#29]
I was reviewing https://stellar.expert/explorer/ledger/15663506
and as you can see, transactions in that ledger contain 100 operations (and are displayed correctly in "ledger view"), yet when clicking on a transaction (for example https://stellar.expert/explorer/tx/ba98d09e265d4263f2a98074719f84e7bb7c290479a58dbaf9584ce91bd39544 ) it only displays 10 operations

expected:
display all operations from a transaction

**Comment by orbitlens** [comment]
Confirmed. 
Thanks for pointing out. Will fix tomorrow.
