### ISSUE TITLE
Tax export: NaN volume in output for network fees and other small transactions

### ISSUE THREAD

**Issue by leighmcculloch** [orbitlens/stellar-expert-explorer#330]
The [tax-export page](https://stellar.expert/tax-export/public) when exporting small value transactions sets the volume as `NaN` rather than the actual volume of the operation/transaction.

To reproduce:
1. Go to https://stellar.expert/tax-export/public
2. Select year `2020`
3. Enter account address `GC4C6VLYABOGRST4G3RH3KXZJ3E7Q3C2FSBHXWMM5FDMI73IZPBWUNYX`
4. Check the `Export transaction fees` checkbox
5. Click `Export data`
6. Click the `Download spending-2020-GC4C6VLYABOGRST4G3RH3KXZJ3E7Q3C2FSBHXWMM5FDMI73IZPBWUNYX.csv` file and save it

The resulting file will contain records like:
```csv
Date,Source,Action,Memo,Symbol,Volume
2020-04-02 19:49:03 +0000,StellarNetwork,SPEND,network fees,XLM,NaN
2020-04-02 19:49:13 +0000,StellarNetwork,SPEND,network fees,XLM,NaN
...
```

The volume column usually contains the amount of XLM that was spent, but instead contains `NaN` for small value spends.

**Comment by orbitlens** [comment]
Fixed in v0.15.19
