### ISSUE TITLE
Tax export: Feature request to include additional fields in tax-export feature

### ISSUE THREAD

**Issue by leighmcculloch** [orbitlens/stellar-expert-explorer#331]
The [tax-export page](https://stellar.expert/tax-export/public) mentions the output is BitcoinTax-compatible data export format, but doesn't make use of all the fields currently available in the format.

The following fields are supported and could be populated:

- `TxHash` – The transaction hash or ID.
- `Sender` – The sending account address.
- `Recipient` – The receiving account address.

There isn't great documentation for the BitcoinTax CSV format, not all fields are documented in the one place, but these fields work and are visible in exports that use the same format.

**Comment by orbitlens** [comment]
I implemented this code about two years ago, and I don't remember stumbling upon these fields in their export/import files. Definitely makes sense to add them.
Thanks for the heads up :+1:

**Comment by leighmcculloch** [comment]
Another field that could be populated is `Account` with a friendly name, something like `Stellar GXXX` or `Stellar GXXX...XXXX` maybe. This is obviously more subjective. Right now because `Account` is not provided it falls back to the `TxSource` value and so the account is specified as `StellarNetwork`.

**Comment by orbitlens** [comment]
Implemented in v0.15.19

> Right now because Account is not provided it falls back to the TxSource value and so the account is specified as StellarNetwork.

BitcoinTax recommends using wallet or exchange name here:

> Source (optional, source or wallet name, e.g. Coinbase or Blockchain)

So we specify "Stellar Network" here to differentiate from CEX trades. I think that after adding `Sender` and `Recipient` fields it will be easy enough for users to differentiate operations.

**Comment by leighmcculloch** [comment]
Thanks @orbitlens!

Regarding Source and Account fields. Where is that snippet from you quoted? I know in 2018 the CSV format had the Source field, but now the CSV fields are listed in the UI as the following. They don't list all fields, but they have Account instead of Source now:

Trading:
```
Date (date and time as YYYY-MM-DD HH:mm:ss Z)
Action (BUY, SELL or SWAP)
Symbol (BTC, LTC, DASH, etc)
Volume (number of coins traded)
Currency (specify currency such as USD, GBP, EUR or coins, BTC or LTC)
Account (override the exchange or wallet name, e.g. Coinbase)
Total (you can use the total Currency amount or price per coin)
Price (price per coin in Currency or blank for lookup)
Fee (any additional costs of the trade)
FeeCurrency (currency of fee if different than Currency)
For example,
Date,Action,Account,Symbol,Volume,Price,Currency,Fee
2020-01-01 13:00:00 -0800,BUY,Coinbase,BTC,1,500,USD,5.50
```
Income:
```
Date (date and time as YYYY-MM-DD HH:mm:ss Z)
Action (INCOME, GIFTIN or MINING)
Account (account or wallet name, e.g. Coinbase or Blockchain)
Symbol (BTC, ETH, LTC, etc)
Volume (number of coins received)
Total (Fair price or value in Currency or your home currency, or blank for market value
Currency (optional, specify alternative to your default currency, such as USD, GBP or EUR)
Memo (optional, name of sender or item sold)
For example,
Date,Action,Account,Symbol,Volume
2020-01-01 13:00:00 -0800,INCOME,"Blockchain Wallet",BTC,
```
Spend:
```
Date (date and time as YYYY-MM-DD HH:mm:ss Z)
Action (SPEND, DONATION or GIFT)
Account (name of account or wallet, e.g. Coinbase or Blockchain)
Symbol (BTC, LTC, ETH, etc)
Volume (number of coins spent)
Total (Fair price or cost in Currency or your home currency, or blank for market value
Currency (optional, specify alternative to your default currency, such as USD, GBP or EUR)
Memo (optional, name of recipient or item purchased)
For example,
Date,Action,Account,Symbol,Volume,Total,Currency
2020-01-01 13:00:00 -0800,SPEND,"Blockchain Wallet",BTC,1,
```

Two benefits of specifying more than `StellarNetwork` in the `Account`:
1. For opening/closing reports it shows where the purchase/income was initiated. Without that the reports say only StellarNetwork and don't break it down.
2. The UI shows the Account and Memo side-by-side. In the CSVs stellar.expert supports the Memo is usually the "other account", and so by setting Account to the main account of hte report, the UI displays the sender/receiver, receiver/sender side-by-side which is nice.

**Comment by leighmcculloch** [comment]
One more benefit:
3. In the gain reports it has columns for 'account acquired' and 'account sold', but when all Stellar accounts have the account name `StellarNetwork` those columns in the gain report is not useful.

**Comment by orbitlens** [comment]
You are right, I was referencing an outdated article from their knowledgebase which didn't contain the `Account` field description. 
Updated the code with `Account`=current account and `Source`="StellarNetwork" (for compatibility).

Thanks for the heads up!
