### ISSUE TITLE
Update home domain isn´t effect

### ISSUE THREAD

**Issue by RASTecnoTI** [orbitlens/stellar-expert-explorer#365]
Hi
I need a help about home domain option. O set the the information on blockchain using the guidance below, but is not reflect on blockchain information:
https://github.com/stellar/docs/blob/master/guides/walkthroughs/how-to-complete-stellar-toml.md

This is my stellar.toml
http://plataformadigitaltrader.com/.well-known/stellar.toml

And this is my issuer account:
GBKRBSL5GD5HQ42P4IOU75BW2OOBSMIHJY2W2VRUYCAM6WVTUPW6HOEI

Thank you

**Comment by RASTecnoTI** [comment]
Hi
I used this checker too

https://stellar.sui.li/toml-check/plataformadigitaltrader.com

**Comment by orbitlens** [comment]
I checked both the account and [issued asset](https://stellar.expert/explorer/public/asset/BDITcoin-GBKRBSL5GD5HQ42P4IOU75BW2OOBSMIHJY2W2VRUYCAM6WVTUPW6HOEI). It seems that everything works as expected now.
Maybe your issue was caused by browser or server caching issues.
