### ISSUE TITLE
Market > Select New Trading Pair > Trades Section not updating correctly

### ISSUE THREAD

**Issue by jpkane** [orbitlens/stellar-expert-explorer#368]
please see attached image…
<img width="1386" alt="StellarExpert___UNI_by_GBDLHPMZVTOVN4W7QWVGWAY5VGFN473HMBFAWRGWRVGSZPCE24KTYUYO" src="https://user-images.githubusercontent.com/21371803/109396048-5303a300-78f5-11eb-9772-74a5b92d78ba.png">

**Comment by orbitlens** [comment]
Fixed in v0.15.21
Thanks for the heads up!

**Comment by jpkane** [comment]
No problem. Thanks for creating such a great stellar blockchain explorer!
