### ISSUE TITLE
Public Network - Potential Missing Trade and Asset Holder on Stellar Expert 

### ISSUE THREAD

**Issue by davewinnyk** [orbitlens/stellar-expert-explorer#384]
Hello, I made a buy offer from an account pk:  GDI44KWFSYJ5Z4NYQO6CF2UW74QWELSR5VL3DXO4I6KK2HAGP2O6MWI2 
to counter a sell offer made by pk: GDVCFTEVZ2SWG5XHRKJLM65JGXXSOXS6YK362SSPIORCOZVBQSGLWJNV

All the assets were exchanged and got to the correct accounts.  (buyer got XLM, seller got TOKE) , but the trade itself  of the assets is not recorded on stellar.expert for the asset, nor in either individual accounts. 
 
additionally, in the buyer account ..MWI2, the change in assets appear as if they happened on Friday, but I processed them today. 

See screen shots below for additional details 

Any advice? 

Here is the trade from Stellar Laboratory: 

"id": "147971939859095553-0",
        "paging_token": "147971939859095553-0",
        "ledger_close_time": "2021-03-15T22:29:26Z",
        "offer_id": "486269424",
        "base_offer_id": "486269424",
        "base_account": "GDVCFTEVZ2SWG5XHRKJLM65JGXXSOXS6YK362SSPIORCOZVBQSGLWJNV",
        "base_amount": "1.1420000",
        "base_asset_type": "native",
        "counter_offer_id": "4759657958286483457",
        "counter_account": "GDI44KWFSYJ5Z4NYQO6CF2UW74QWELSR5VL3DXO4I6KK2HAGP2O6MWI2",
        "counter_amount": "5.7099942",
        "counter_asset_type": "credit_alphanum4",
        "counter_asset_code": "TOKE",
        "counter_asset_issuer": "GAASD6MEPCGI6J7HUZR7PKYN3V54P7ODIHDNRNCDQURCRDBTZ5AQYIJP",
        "base_is_seller": true,
        "price": {
          "n": 999979,
          "d": 199996" 
![Toke drop](https://user-images.githubusercontent.com/70180828/111232672-97f82c80-85b9-11eb-9aae-e17647319385.PNG)
![No trade on TOKE page](https://user-images.githubusercontent.com/70180828/111232675-99c1f000-85b9-11eb-831a-9954a3208f8e.PNG)

**Comment by davewinnyk** [comment]
This updated after about 20 hours.

**Comment by bahmanmorad** [comment]
Hi, I have not received anything so far


Sent from Yahoo Mail for iPhone$&@


On Tuesday, March 16, 2021, 7:57 PM, davewinnyk ***@***.***> wrote:




Closed #384.

**Comment by orbitlens** [comment]
We had a temporary ledger ingestion problem. Right now everything is back in sync with the network. Sorry for the inconvenience.

**Comment by bahmanmorad** [comment]
Thank you for following up. I will inform you whenever I receive,


Sent from Yahoo Mail for iPhone$&@


On Tuesday, March 16, 2021, 8:32 PM, orbitlens ***@***.***> wrote:




We had a temporary ledger ingestion problem. Right now everything is back in sync with the network. Sorry for the inconvenience.
