### ISSUE TITLE
Transactions not showing on Stellar Expert.

### ISSUE THREAD

**Issue by ThanePropertyInvestmentsLtd** [orbitlens/stellar-expert-explorer#386]
at least 2 No transactions 0n the 15th march not showing on  stellar expert for TPI.

https://stellar.expert/explorer/public/asset/TPI-GAOCNOS2AUPGZZ4Q2EF7KAV3BDL5GBKQWUUN3O3OSUYAXLOUM3Z6HICW-1?filter=all

**Comment by bahmanmorad** [comment]
Hi tank you for responding


Sent from Yahoo Mail for iPhone$&@


On Tuesday, March 16, 2021, 5:33 PM, Thane Property Investments Ltd ***@***.***> wrote:




at least 2 No transactions 0n the 15th march not showing on stellar expert for TPI.

https://stellar.expert/explorer/public/asset/TPI-GAOCNOS2AUPGZZ4Q2EF7KAV3BDL5GBKQWUUN3O3OSUYAXLOUM3Z6HICW-1?filter=all

**Comment by ThanePropertyInvestmentsLtd** [comment]
is there a problem with their network.

**Comment by bahmanmorad** [comment]
You are right

**Comment by orbitlens** [comment]
@ThanePropertyInvestmentsLtd We had a temporary ledger ingestion problem. Right now everything is back in sync with the network. Sorry for the inconvenience.

**Comment by ThanePropertyInvestmentsLtd** [comment]
Fine now. All transactions are showing.
