### ISSUE TITLE
Unhandled error on iPhone 

### ISSUE THREAD

**Issue by Sellucius** [orbitlens/stellar-expert-explorer#389]
Hi,

When browsing on Stellar Expert, after a few page clicks this message pops up. It’s incredibly annoying, almost renders Expert useless on iPhone. Refreshing the page 10 times sometimes works. Leaving the pace for another, then return en hit refresh sometimes helps. Only experiencing this on iPhone (I have an 11 Pro max)
No idea what it is, it’s not the cache as I emptied that just before opening Expert.

![E347BF28-FEDF-4202-AFF4-5880370196D9](https://user-images.githubusercontent.com/71544850/111861231-f40dd880-894c-11eb-953c-fc1b9c83f396.png)

Please check and resolve? Thanks for your help!

**Comment by orbitlens** [comment]
Hey, 
We couldn't reproduce the problem in our test environment, but we rolled out an update that should fix it. 
Could you please try to navigate to the page that produces an error and check whether the problem remains, clicking here and there?
_(Please refresh the page before checking as the browser may show the old version from the cache)_

**Comment by Sellucius** [comment]
You have no idea how happy you just made me...I use expert a lot, and it was so frustrating to experience that after a few clicks (only on iPhone) all got messed up. Your update worked, all works fine now. If it ever happens again, I’ll contact you.

You guys accept donations? I’m a partner at SureRemit and I want to send you some RMT, your service has helped us a lot. Just a way of saying thanks.

Thanks again for fixing this!
Selwyn

Met vriendelijke groet,
Selwyn Paehlig

M: +31 (0)6555 00665
E:  ***@***.***

**Comment by orbitlens** [comment]
It's awesome to hear that everything works 👍 
Please do not hesitate to contact us if you spot any other bug or if you have feature requests. Any feedback is much appreciated.

re: _You guys accept donations?_
Yes, here is our piggy bank account we use to cover server costs: `GDQ75AS5VSH3ZHZI3P4TAVAOOSNHN346KXJOPZVQMMS27KNCC5TOQEXP`
Thanks

**Comment by Sellucius** [comment]
Thanks for your help! I’ve sent over a little donation!

Met vriendelijke groet,
Selwyn Paehlig

M: +31 (0)6555 00665
E:  ***@***.***

**Comment by Sellucius** [comment]
Hi friends,

Last two days it seems that Stellar Expert is not updated on the blockchain activity. Are you aware of this?

Thanks,
Selwyn

Met vriendelijke groet,
Selwyn Paehlig

M: +31 (0)6555 00665
E:  ***@***.***

**Comment by orbitlens** [comment]
Everything is ok on our side. Double checked from different devices and networks.

Maybe some cache-related issues. I initiated a cache purge procedure, the content will be fully refreshed across all CDN endpoints within a few minutes. Please let me know if this fixes the issue for you. If not, we'll try digging through server logs.
