### ISSUE TITLE
Missing lumens

### ISSUE THREAD

**Issue by nathanjc2000** [orbitlens/stellar-expert-explorer#39]
I have tried to transfer lumens to a Bittrex wallet and they gone missing how can I get them back?

**Comment by nathanjc2000** [comment]
I sent them on 02nd feb

**Comment by orbitlens** [comment]
1. Copy-paste your account address (starts with "G...") into the search
field on https://stellar.expert website.
2. Find your transaction in the list of account operations and click it.
3. You will see transaction details. Copy transaction hash and send to the
Bittrex support. Do not forget to mention your account address in the
support ticket.
4. Wait. They are overloaded with support requests, so they may response in
week or two.

Regards,
StellarExpert support team

**Comment by nathanjc2000** [comment]
Thanks, should is put the address i was sending from or the address I was sending to? 
Thanks
Nathan
