### ISSUE TITLE
failed transfer issue

### ISSUE THREAD

**Issue by mashloum** [orbitlens/stellar-expert-explorer#399]
HI, My transfer from coinbase pro to bittrex account failed, however I dont see the fund in my account, 
all data items are correct, but the transaction failed 
this is the transaction hash
https://stellar.expert/explorer/public/tx/56e6403d122ca53b67e0fbd517b738b9fe275229121885b25cf91e4d4701cd3b

Thanks.

**Comment by orbitlens** [comment]
Hello,
Judging from the transaction result, the payment failed because you didn't have enough funds on the account balance at the moment when the transaction has been submitted. It failed, so funds shouldn't be deducted from your balance.
