### ISSUE TITLE
Tx links are broken

### ISSUE THREAD

**Issue by dexterlohnes** [orbitlens/stellar-expert-explorer#42]
1) Go to stellar.expert (either public or testnet).
2) Click a link for an operation in the Recent Operations panel.
3) Link will give you a 404 error.

This is a result of an extra "/" character in the URL right before "tx".

For example: https://stellar.expert/explorer/testnet//tx/5a7b1b4e378ccafa137c680ee45f5103b926c220922bc4df70b26a4b98e9020a

**Comment by orbitlens** [comment]
Fixed
