### ISSUE TITLE
Transaction datetime stamp out by 1 hour (for me anyway)

### ISSUE THREAD

**Issue by Synesso** [orbitlens/stellar-expert-explorer#46]
I'm in UTC+10 and the most recent transactions appear with a datetime of 1 hour ago (UTC+9). How are the times calculated?

**Comment by Synesso** [comment]
Latest op 6 secs ago
<img width="424" alt="screen shot 2018-02-18 at 8 35 30 pm" src="https://user-images.githubusercontent.com/21859/36350870-617e6544-14eb-11e8-8254-f39dfdf4d3cf.png">

Current local time was 20:35. Expert shows 19:35.
<img width="487" alt="screen shot 2018-02-18 at 8 37 30 pm" src="https://user-images.githubusercontent.com/21859/36350879-95e0653a-14eb-11e8-9649-7b50f8755bda.png">

**Comment by nebolsin** [comment]
Same issue here in UTC+3, seems to only affect operations list.

<img width="1278" alt="screenshot_2018-02-23_20_20_49" src="https://user-images.githubusercontent.com/10788/36607439-b095b78c-18d7-11e8-912a-c4ecf751f5ee.png">

**Comment by orbitlens** [comment]
Looks like a server configuration issue (it is located in UTC+1 timezone). Will check. 
Thanks for reporting.
