### ISSUE TITLE
Incorrect Operations threshold help link

### ISSUE THREAD

**Issue by popko** [orbitlens/stellar-expert-explorer#48]
Actual behavior: In account page -> Summary subsection -> "Operation thresholds" -> question mark help text -> link"Read more..." points to https://www.stellar.org/developers/guides/concepts/accounts.html#sequence-number

Expected behavior: The link should point to https://www.stellar.org/developers/guides/concepts/accounts.html#thresholds

**Comment by orbitlens** [comment]
Fixed. 
Thanks!
