### ISSUE TITLE
Links to other accounts don't fully update page

### ISSUE THREAD

**Issue by dexterlohnes** [orbitlens/stellar-expert-explorer#51]
In short, the issue is that if you are on an account page and click a link to another account, the account  information pane does not fully update. 

Steps to reproduce. 

1) Visit any account, such as [by clicking here](https://stellar.expert/explorer/public/account/GBSO63GMXZKXGY3XL3SMQIQJ2JHK4USIABOOXWXZD7P3FCLHNY7Q64XS)
2) Find an "account debited" or "accounted credit" listing, such as [here](https://cl.ly/2m2h2K0d301j)
3) Click the link for the account in the "Details" column.

Expected outcome: The page should update to all new information.
Actual outcome: The URL for the web browser updates, but the information shown in the browser does not actually update. 

I've reproduced this on OSX on both Opera and Chrome browsers.

**Comment by orbitlens** [comment]
Fixed.
