### ISSUE TITLE
Clicking on an operation should take you to the transaction details

### ISSUE THREAD

**Issue by mfontanini** [orbitlens/stellar-expert-explorer#52]
Currently if you're looking at an account and you see the list of effects/payments and you click on one of the links (e.g. "Account debited"), instead of taking you into the transaction details, it takes you to the ledger details so then you have to scroll down to find the tx and see the details.

Shouldn't clicking that take you straight into the transaction? The transaction view already has a link to the ledger it belongs to so I'm not sure why the workflow is this way.

**Comment by orbitlens** [comment]
Yes, definitely it would be better.

**Comment by mfontanini** [comment]
By the way, I really like how stellar.expert is looking, both visually and all the new features I see popping up. It seems like you're putting a lot of work into it, great job!
