### ISSUE TITLE
Trying to check invalid account gets stuck

### ISSUE THREAD

**Issue by mfontanini** [orbitlens/stellar-expert-explorer#54]
Search for a valid public address belonging to an account which is not created yet. Instead of getting some message saying "Account does not exist" you get an infinite spinner.

e.g. https://stellar.expert/explorer/public/account/GBW74UVOXKGHO3WX6AV5ZGTB4JYBKCEJOUQAUSI25NRO3PKY5BC7WYZS

**Comment by orbitlens** [comment]
Fixed.
