### ISSUE TITLE
Sent myself 105 Billion XLM.. 

### ISSUE THREAD

**Issue by BlockEq** [orbitlens/stellar-expert-explorer#58]
https://stellar.expert/explorer/public/account/GA2HB3PRIKRDHJPJE54MLC5MCSRSHUPIKF2XIAOD4UIXQWGTWTIPHFB7

April Fools (?)

**Comment by orbitlens** [comment]
Confirmed on both, public and test networks. 
Looks like a StellarCore bug to me. Definitely should be reported [here](https://github.com/stellar/stellar-core/issues).
