### ISSUE TITLE
navigate to operation

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#59]
It would be great to navigate to an operation with a direct link. 

With that said, given that there's no existing operation specific page, a low hanging fruit is to add operation anchors to the transaction pages. 

So something like https://stellar.expert/explorer/public/tx/cbf8b4d60203bcf5d6ac2ea5466801642d798862cd6a576fc3448b310c3d13ed#73730543929286657

Would take to the tx page, straight to a the specific operation `<div>`. In a perfect world - it would even highlight or otherwise mark that specific operation.

**Comment by orbitlens** [comment]
Implemented
