### ISSUE TITLE
linear scale for account balances

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#60]
the logarithmic scale can be confusing in regards to understanding actual trends

**Comment by orbitlens** [comment]
Agree. However, the linear scale looks very poor if an account holds a substantial amount of some asset. 

I'll add a switch `linear|logarithmic scale`. By default, a linear scale will be used.

**Comment by tomerweller** [comment]
Yeah, a switch would be great. 

I think that the root cause of this issue is displaying multiple assets on the same scale. A possible long term solution is introduce multiple scales (similar tho how coinmarketcap do it in history price charts with USD and BTC).

**Comment by orbitlens** [comment]
I stumbled on a few accounts that own more than 20 different assets. In case of multiple assets the page may become clogged with charts. 

What about a dropdown with asset selector? By default the chart shows all assets in linear scale. A user can switch between *log* and *linear* scale and choose a single asset to show on the chart, hiding all other. Both a switch and dropdown are located under the chart.

What do you think?

**Comment by tomerweller** [comment]
Yeah, I share your concern.

I think there's very little value in having multiple asset balance history on the same chart when the scales are not individually adjusted (like the cointmarketcap example). Furthermore, even if the scales are adjusted - I'm not sure this is actually important - when do we care about the ratio between the different asset balances for the same account? maybe for super specific market making accounts.

Here's a proposal for a low hanging fruit solution: 
Have a single chart, linear scale, with a single asset that defaults to XLM.
Below that - a list of all other assets, along with current balances. When you click on one of them, the chart changes it's data to that asset balance history. 

A more comprehensive, yet not necessarily better solution is to have a dropdown like you suggest, but with check-boxes. All checked assets will be displayed together, but with the scale adjusted individually.

**Comment by orbitlens** [comment]
Implemented
