### ISSUE TITLE
Querying by federated address

### ISSUE THREAD

**Issue by alien35** [orbitlens/stellar-expert-explorer#61]
Hey guys, the open API is great. I am wondering if being able to query a federated address, for instance `test@music*lumenbox.org` is in the roadmap. Ideally, it would be able to query both the Public Key and Memo.

**Comment by orbitlens** [comment]
Sure. 
Will add the federation address resolver in the next release.

**Comment by chriserice** [comment]
+1 on the suggestion.

**Comment by orbitlens** [comment]
Fixed in `v0.8.31`
@alien35 sorry for such a delay. Completely forgot about that issues as I was focused on critical system refactoring and API standardization.
