### ISSUE TITLE
Our domain does not come across as verified despite the stellar.toml CORS headers being as requested

### ISSUE THREAD

**Issue by mvastani** [orbitlens/stellar-expert-explorer#65]
when we use curl to inspect the CORS directives in the header we see this:
HTTP/2 200 
date: Wed, 27 Jun 2018 21:47:00 GMT
content-type: text/plain
content-length: 263
last-modified: Thu, 26 Apr 2018 21:42:29 GMT
accept-ranges: bytes
etag: "80d06779a7ddd31:0"
server: Microsoft-IIS/10.0
access-control-allow-origin: *
But Stellar.expert web view shows our token as not verified. Any suggestions on a possible fix?
ASSET: KAVA-GD4T35DMXYDE7BJWYPUWK43VFJO5IBUQYG2YGMICPTWP4JTNWQELKAVA
TOML FILE: https://kava.world/.well-known/stellar.toml

**Comment by orbitlens** [comment]
I tried to open your [asset page](https://stellar.expert/explorer/public/asset/KAVA-GD4T35DMXYDE7BJWYPUWK43VFJO5IBUQYG2YGMICPTWP4JTNWQELKAVA) in browser (Chrome) and saw the following error in console:

```
Failed to load https://kava.world/.well-known/stellar.toml: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. 
Origin 'https://stellar.expert' is therefore not allowed access. 
Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

It looks like your 'Access-Control-Allow-Origin' header does not match CORS specification.

**Comment by mvastani** [comment]
Thank you! That fixed the issue. 
Best
-minaz
