### ISSUE TITLE
lumenaut inflation pool payments not showing up

### ISSUE THREAD

**Issue by henderob** [orbitlens/stellar-expert-explorer#67]
The most recent lumenaut inflation pool payments (~ jul 10) are not showing up in payment history.

**Comment by orbitlens** [comment]
Hey @henderob 

There is an announcement on [stellar.expert](https://stellar.expert) main page:

> Stats and effects history for the recent ledgers (since 2018-07-03 21:56:38 UTC) are temporary unavailable. Blockchain explorer functionality (ledgers, transactions, operations, accounts) is unaffected. Sorry for any inconveniences.

Hopefully, the service will be fully synced with the ledger by July 16.

Testnet data is fully synced with the ledger (you can use it), but livenet database is in inconsistent state, so I decided to reingest the whole ledger history with my new aggregation engine. The databases for both livenet and testnet already grew up to 350 GB (Core and Horizon with my auxiliary tables and materialized stats views) consuming almost all available space on my server SSD disk array. Therefore I need to switch to optimized minimalistic version of history database.

Sorry for temprorary service disruption.
