### ISSUE TITLE
is it possible to pair a specific public key with a  secret key?

### ISSUE THREAD

**Issue by simonebonn** [orbitlens/stellar-expert-explorer#68]
Hi, I sent a small amount of lumen to a wrong public key, which doesn't look to exist jet. So, I would like to create a new account using this public key: in this way I hope to recover my lumen. Is it possible to do this? Or any idea how to resolve this issue?
Thank you in advance!

**Comment by orbitlens** [comment]
No, it's impossible. Without secret key you will never access your account (at least not in the nearest 15 years, until quantum computers powerful enough to pick up your secret key are invented). 
If you entered someone's else valid Stellar address, you can ask this person to send your lumens back. 
Stellar network won't accept transaction to invalid address, so if you sent XLM to some random sequence of characters, the transaction will fail, and your funds will be returned to your account.
