### ISSUE TITLE
href links not behaving as expected 

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#72]
Clicking on a link while holding the CTRL key (CMD on OSX) should open the link in a new tab. In stellar expert it opens it in the same tab.

I haven't dug too deep into it but I'm assuming these clicks are intercepted for some custom handling. Would be happy to help think of alternatives if you share the requirements.

**Comment by orbitlens** [comment]
Yes, you are absolutely right. I completely forgot about `Ctrl+Click` as I'm using `mouse wheel press` action to open a link in a new tab. Link clicks interception is required for the single-page application routing.

Fixed in `0.8.4`.
