### ISSUE TITLE
Invalid Total Payments/Trades 

### ISSUE THREAD

**Issue by dolcalmi** [orbitlens/stellar-expert-explorer#74]
Total payments and Total trades are not showing the correct value

**Comment by orbitlens** [comment]
Could you please provide a link of the asset|account that shows incorrect stat counters?

**Comment by dolcalmi** [comment]
https://stellar.expert/explorer/public/account/GAWB5QMEQ2U2I22KCYIU5H5SBUUBUFAWOCSCJ5JLSQU5UOZG65HLFUND?filter=transfers

https://stellar.expert/explorer/public/account/GASNBEMVPNGCV3NQXHB7VYRRA57PVVD5JFBOSWHOONGE4WKRPUUN3JBX

in general all accounts. Please check graphs and totals

**Comment by orbitlens** [comment]
Ah, you are right, totally wrong numbers. Daily stats instead of running total. 
Thanks for pointing out!!!

Fixed in `0.8.6`
