### ISSUE TITLE
Operation details mixed with other op/tx

### ISSUE THREAD

**Issue by dolcalmi** [orbitlens/stellar-expert-explorer#76]
Please check attached image
![mixed details op 2018-08-10 10-05-54](https://user-images.githubusercontent.com/2079600/43965696-8f45d490-9c85-11e8-8c4f-4b135c9684e1.png)

is a path payment of XLM but details shows a DRA transaction. if I click in operation (83265397096235009) it shows https://stellar.expert/explorer/public/tx/83265397096235008#83265397096235009 but the real transaction is https://steexp.com/tx/51804d1a22e577145eaa03b7a5d21e8bd75c12316115251c69241eaa4641fb5a

if you need more info let me know

**Comment by orbitlens** [comment]
Fixed in `0.8.8`
