### ISSUE TITLE
Order book view does not default to XLM pair

### ISSUE THREAD

**Issue by chriserice** [orbitlens/stellar-expert-explorer#78]
The behavior of the order book view has changed at least for apay.io. Prior to the downtime, the view defaulted to the XLM pair. In apay.io's [BTC order book](https://stellar.expert/explorer/public/asset/BTC-GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF?filter=orderbook) today, the default is BCH pair. Is there a way to change back to XLM trading pair? Thanks!

**Comment by orbitlens** [comment]
Fixed in `v0.8.10`
