### ISSUE TITLE
Put bed memo in Stellar XLM translation 

### ISSUE THREAD

**Issue by morvolo** [orbitlens/stellar-expert-explorer#79]
Transaction e6c67093028a314b50f7234c8fb156273defa0774092ed6078e87533ea893b59
Date	Aug. 23, 2018 - 06:17 PM
Account	Atenzio*lobstr.co
Account username	Atenzio
Amount	19 XLM (190000000.0 stroops)
Amount (USD)	$ 4.04
Destination	GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A
Transaction type	Payment
Ledger index	19614077
Message	lobster mobile 

Supposed to be: 1018236442

**Comment by orbitlens** [comment]
`GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A` is the address of Binance Exchange. Contact their support directly and they will process your deposit manually.
