### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by orbitlens** [orbitlens/stellar-expert-explorer#81]
From email:
> Please add a toggle to enable night mode with a black background.

**Comment by Mansarde** [comment]
I second that!
I do appreciate a light design during the day, but during the later hours it burns out my eyes. 😫

**Comment by fishcharlie** [comment]
It'd be great if this feature supported the [`prefers-color-scheme` CSS media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) for operating systems and browsers that support dark mode to have it enabled by default.

**Comment by orbitlens** [comment]
Implemented in v12.8

**Comment by fishcharlie** [comment]
@orbitlens Does this use `prefers-color-scheme`? Looks like it's only an option in the footer and doesn't respect the OS level setting.

**Comment by orbitlens** [comment]
> @orbitlens Does this use `prefers-color-scheme`? Looks like it's only an option in the footer and doesn't respect the OS level setting.

@fishcharlie We are using `window.matchMedia('(prefers-color-scheme: dark)').matches` query to detect dark mode preferences in runtime from the JS code. So in theory it should work if dark mode is set on the OS/browser level.

**Comment by Mansarde** [comment]
> Implemented in v12.8

Just curious where we can find it?
The last commit was from 29 days ago and I don't see any other branch.
