### ISSUE TITLE
Trust Line Attacks

### ISSUE THREAD

**Issue by JonLister** [orbitlens/stellar-expert-explorer#83]
Hello Orbitlens,

I just created this as an issue on Stellar, but figured I would share with you as well. I found a potential issue which could lead to abuse (Trust Line Attacks).

Users could target an anchor or individual by adding trust lines to maliciously named tokens. So when users search the victim's address on an explorer they see all the spam tokens created by the attacker. Here's an example:

https://stellar.expert/explorer/public/account/GB6A5WRAINJK5HNDOWA2G3RH22P2MQVOEBFIMQF3QTNMXDM2DQK2GO6N

Maybe this could be resolved by only displaying assets that have a supply > 0

**Comment by orbitlens** [comment]
Hey Jon,

Thanks for reporting. Yes, I know that the problem with trustline names exists, and it may be much more severe than just obscene token names. 
Attackers use asset name spoofing to mimic popular assets. For example, I heard that someone is selling fake MOBI tokens.

However, I don't think that just hiding assets with zero supply or without trustlines makes any sense. From the technical point of view, there are no difficulties in issuing malicious assets with large supply and a few trustlines, it can be achieved by using 3-4 accounts that create trustlines to each other.

It's much easier for wallets to support the whitelist of "genuine" assets, but I can't think of any adequate solution for StellarExpert, as it is used by developers and researchers. Hiding any information from them may result in a non-deterministic behavior.

I think that this problem has to be addressed by SDF on the protocol level.

**Comment by orbitlens** [comment]
Ref https://github.com/stellar/stellar-protocol/issues/176

**Comment by orbitlens** [comment]
Fixed in `0.8.17`
