### ISSUE TITLE
Cosmetic issue: weights overlaps signer address in Safari

### ISSUE THREAD

**Issue by chriserice** [orbitlens/stellar-expert-explorer#84]
![screen shot 2018-09-30 at 11 50 35 am](https://user-images.githubusercontent.com/19399505/46261361-546fdd80-c4a7-11e8-8f03-0afc594c915b.png)

Slight cosmetic issue in signers section where the weight of signing key overlaps the key. See attached. I'm using Safari 12.0. 🙂

**Comment by orbitlens** [comment]
Fixed in `0.8.18`
