### ISSUE TITLE
Asset Page improvements 

### ISSUE THREAD

**Issue by tomerweller** [orbitlens/stellar-expert-explorer#87]
- [x] Asset page should include asset flags (auth_required, revocable, immutable). You can follow  issuing account link to see this but it would be more comfortable if it's also in the asset page.
- [x] `Asset holders` currently shows the number of total trustlines. Ideally, this should be the number of trustlines that have a balance>0.
- [x] To complete the picture, it would be great to also have the total number of trustlines.
- [x] In the case of a restricted asset, indicate how many of these are authorized.

**Comment by tomerweller** [comment]
Thanks @orbitlens. Yeah, I can see why the authorization status might need some more work. I removed that from the 3rd item and added it to a 4th. Are 1-3 achievable with your current schema?

**Comment by orbitlens** [comment]
Sure. Going to implement and release this functionality in two weeks.

**Comment by tomerweller** [comment]
Thinking out loud: `AUTH_REQUIRED=false` and `AUTH_REVOCABLE=false` are misleading in the (common) case where  `AUTH_IMMUTABLE=false`, since the issuer can change at anytime. 

I wonder if there's a way to indicate that without being not too intrusive. Maybe a red flag that on hover explains that?

**Comment by orbitlens** [comment]
`AUTH_REQUIRED` and `AUTH_REVOCABLE` flags added to the asset page in `v0.8.23`. 
There is a problem with `AUTH_IMMUTABLE`, as [Horizon doesn't return the value of this flag](https://github.com/stellar/go/issues/743).

The remaining three features require [ingestion engine refactor](https://github.com/orbitlens/stellar-expert-explorer/issues/98).

**Comment by tomerweller** [comment]
@orbitlens `auth_immutable` is now in horizon (master)

**Comment by orbitlens** [comment]
Implemented in v0.10.7
