### ISSUE TITLE
Improve Asset Discoverability 

### ISSUE THREAD

**Issue by lkbell** [orbitlens/stellar-expert-explorer#88]
First- Incredible application.  Really slick functionality and enjoyable UI.  Thank you for your work here.  

**Feedback**
At present, finding a specific asset that exists on the Stellar network is a little difficult, particularly when a user may not already know about the asset.  As an example, think of the use case where a user wants to know, "Is there a tokenized version of XX fiat currency available on Stellar?"  or "Is there an anchor offering YY (non-native asset) on the Stellar network right now?"  At present, there's no intuitive way to answer these questions and get a user pointed to the correct Asset Page quickly.  

**Possible Implementation** 
1) Add Asset Search functionality to existing "All Assets" page, enable users to search by Asset ticker, issuer name, etc
2) Add ability to search for token tickers and/or anchor name to the existing general search box accessible from all pages (currently can only search by transaction hash, account address, or ledger sequence)
3) Implement an asset categorization scheme functionality (similar to what StellarX has done in attached screenshot) to help users sort through and discover tokens of interest.  

<img width="1080" alt="screen shot 2018-10-09 at 11 59 09 am" src="https://user-images.githubusercontent.com/43968334/46692875-3304a500-cbbd-11e8-8b1d-16512360ba6c.png">

Thank you.

**Comment by orbitlens** [comment]
> Add ability to search for token tickers and/or anchor name to the existing general search box accessible from all pages (currently can only search by transaction hash, account address, or ledger sequence)

I think it's the best option. I'm going to add lookup by asset code to the search-box. 

As for the scenario where user knows the account address, it can be done in two steps: copy-paste the issuer address to the search-box, and then navigate to the asset directly from the account page.

**Comment by lkbell** [comment]
Thanks @orbitlens.  Agree that "asset discovery" is easy enough when a user already knows:
1) Some asset exists and 
2) Info (such as account address) about the issuer of that asset

I think the more compelling case is making it easier for users to discover the breadth of assets available on Stellar and drill down on an asset of interest to learn more.   Hopefully the search functionality you mentioned will improve this process!

**Comment by orbitlens** [comment]
Implemented in `v0.8.21`
