### ISSUE TITLE
Asset Holders vs Trustlines

### ISSUE THREAD

**Issue by jeffditullio** [orbitlens/stellar-expert-explorer#89]
Asset holders should be those with balance > 0 rather than the existence of a trustline.
For example:
https://stellar.expert/explorer/public/asset/USD-GBSTRUSD7IRX73RQZBL3RQUH6KS3O4NYFY3QCALDLZD77XMZOPWAVTUK
the info on the top left and asset holders on the graph is misleading. Number of trustlines is interesting as well. I recommend showing: asset holders and trustlines on the top left text and then just asset holders on the graph.

**Comment by orbitlens** [comment]
Duplicates #87
