### ISSUE TITLE
Trades for Offer

### ISSUE THREAD

**Issue by jeffditullio** [orbitlens/stellar-expert-explorer#90]
When showing a manage (create/update/remove) offer it would be nice to drill down to show all the corresponding trades that may have happened for that offer. It's nice that you show the effects but if I understand correctly those are only if the offer has an immediate effect when it makes its way into the ledger, so it's hard to determine which offers eventually caused a trade.

**Comment by orbitlens** [comment]
Implemented in v0.12 for update/remove offer operations. For create offer case the links in the operation description will be available once #188 is implemented.
At this point all offers (including deleted) with full trades and changes history can be explored using search box.
