### ISSUE TITLE
Asset Recent Trades

### ISSUE THREAD

**Issue by jeffditullio** [orbitlens/stellar-expert-explorer#94]
For Asset page trades tab, it would be more useful to show trades rather than manage offers.

**Comment by orbitlens** [comment]
Implemented in `v0.8.34`

**Comment by orbitlens** [comment]
Fixed trades API performance, now it fetches data in fractions of a second for all assets. 
Thanks for pointing out that problem! 

Trades with zero traded amount are completely normal. That's the result of the recent protocol change in Stellar Core v10. You can find a formal description of the updated offers crossing behavior in [CAP-0004](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0004.md).

**Comment by jeffditullio** [comment]
@orbitlens wrt 2 - thanks for the link! I see, that account was continually creating new offers that crossed the existing book and because it was the smallest it created a trade (rounded to zero aka not executed entirely) and offer removed from book.

From the CAP "Third, the offer which initially had less total value is removed from the book regardless of whether it has been executed entirely."
