### ISSUE TITLE
Operations Fail to Load for Large Accounts

### ISSUE THREAD

**Issue by jeffditullio** [orbitlens/stellar-expert-explorer#96]
For example "all operations" never loads for https://stellar.expert/explorer/public/account/GAGA7RRXJ3PBP2COTU7O5FMNDDZUXWVO7RWYWR2XODEAZVRJAWZEYMQ4

**Comment by orbitlens** [comment]
Fixed in `v0.8.20`
Thanks for reporting the problem!
